//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_CONSULTAS.ProxyConsultas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeccionDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ESCUELA")]
    [System.SerializableAttribute()]
    public partial class SeccionDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_GradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_ProfesorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_SeccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Est_SeccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_SeccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Turno_ProfesorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_Grado {
            get {
                return this.Cod_GradoField;
            }
            set {
                if ((this.Cod_GradoField.Equals(value) != true)) {
                    this.Cod_GradoField = value;
                    this.RaisePropertyChanged("Cod_Grado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_Profesor {
            get {
                return this.Cod_ProfesorField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_ProfesorField, value) != true)) {
                    this.Cod_ProfesorField = value;
                    this.RaisePropertyChanged("Cod_Profesor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_Seccion {
            get {
                return this.Cod_SeccionField;
            }
            set {
                if ((this.Cod_SeccionField.Equals(value) != true)) {
                    this.Cod_SeccionField = value;
                    this.RaisePropertyChanged("Cod_Seccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Est_Seccion {
            get {
                return this.Est_SeccionField;
            }
            set {
                if ((this.Est_SeccionField.Equals(value) != true)) {
                    this.Est_SeccionField = value;
                    this.RaisePropertyChanged("Est_Seccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Seccion {
            get {
                return this.Nom_SeccionField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_SeccionField, value) != true)) {
                    this.Nom_SeccionField = value;
                    this.RaisePropertyChanged("Nom_Seccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Turno_Profesor {
            get {
                return this.Turno_ProfesorField;
            }
            set {
                if ((object.ReferenceEquals(this.Turno_ProfesorField, value) != true)) {
                    this.Turno_ProfesorField = value;
                    this.RaisePropertyChanged("Turno_Profesor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatriculaDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ESCUELA")]
    [System.SerializableAttribute()]
    public partial class MatriculaDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_EstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellNom_venField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_MATRICULAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DNI_ESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ESTADO_MATRIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FEC_MATRIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_SECCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_EstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_SeccField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_Est {
            get {
                return this.Ape_EstField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_EstField, value) != true)) {
                    this.Ape_EstField = value;
                    this.RaisePropertyChanged("Ape_Est");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellNom_ven {
            get {
                return this.ApellNom_venField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellNom_venField, value) != true)) {
                    this.ApellNom_venField = value;
                    this.RaisePropertyChanged("ApellNom_ven");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COD_MATRICULA {
            get {
                return this.COD_MATRICULAField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_MATRICULAField, value) != true)) {
                    this.COD_MATRICULAField = value;
                    this.RaisePropertyChanged("COD_MATRICULA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DNI_EST {
            get {
                return this.DNI_ESTField;
            }
            set {
                if ((this.DNI_ESTField.Equals(value) != true)) {
                    this.DNI_ESTField = value;
                    this.RaisePropertyChanged("DNI_EST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ESTADO_MATRI {
            get {
                return this.ESTADO_MATRIField;
            }
            set {
                if ((this.ESTADO_MATRIField.Equals(value) != true)) {
                    this.ESTADO_MATRIField = value;
                    this.RaisePropertyChanged("ESTADO_MATRI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FEC_MATRI {
            get {
                return this.FEC_MATRIField;
            }
            set {
                if ((this.FEC_MATRIField.Equals(value) != true)) {
                    this.FEC_MATRIField = value;
                    this.RaisePropertyChanged("FEC_MATRI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Registro {
            get {
                return this.Fec_RegistroField;
            }
            set {
                if ((this.Fec_RegistroField.Equals(value) != true)) {
                    this.Fec_RegistroField = value;
                    this.RaisePropertyChanged("Fec_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod {
            get {
                return this.Fec_Ult_ModField;
            }
            set {
                if ((this.Fec_Ult_ModField.Equals(value) != true)) {
                    this.Fec_Ult_ModField = value;
                    this.RaisePropertyChanged("Fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_SECCION {
            get {
                return this.ID_SECCIONField;
            }
            set {
                if ((this.ID_SECCIONField.Equals(value) != true)) {
                    this.ID_SECCIONField = value;
                    this.RaisePropertyChanged("ID_SECCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Est {
            get {
                return this.Nom_EstField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_EstField, value) != true)) {
                    this.Nom_EstField = value;
                    this.RaisePropertyChanged("Nom_Est");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Secc {
            get {
                return this.Nom_SeccField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_SeccField, value) != true)) {
                    this.Nom_SeccField = value;
                    this.RaisePropertyChanged("Nom_Secc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfesorDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ESCUELA")]
    [System.SerializableAttribute()]
    public partial class ProfesorDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APE_PROFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeNom_ProfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_PROFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CORREO_PROFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DEPARTAMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DISTRITOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNI_PROFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESPECIALIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ESTADO_PROFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FOTO_PROFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_UBIGEOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOM_PROFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROVINCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEXO_PROFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TELF_PROFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APE_PROF {
            get {
                return this.APE_PROFField;
            }
            set {
                if ((object.ReferenceEquals(this.APE_PROFField, value) != true)) {
                    this.APE_PROFField = value;
                    this.RaisePropertyChanged("APE_PROF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeNom_Prof {
            get {
                return this.ApeNom_ProfField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeNom_ProfField, value) != true)) {
                    this.ApeNom_ProfField = value;
                    this.RaisePropertyChanged("ApeNom_Prof");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COD_PROF {
            get {
                return this.COD_PROFField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_PROFField, value) != true)) {
                    this.COD_PROFField = value;
                    this.RaisePropertyChanged("COD_PROF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CORREO_PROF {
            get {
                return this.CORREO_PROFField;
            }
            set {
                if ((object.ReferenceEquals(this.CORREO_PROFField, value) != true)) {
                    this.CORREO_PROFField = value;
                    this.RaisePropertyChanged("CORREO_PROF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DEPARTAMENTO {
            get {
                return this.DEPARTAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.DEPARTAMENTOField, value) != true)) {
                    this.DEPARTAMENTOField = value;
                    this.RaisePropertyChanged("DEPARTAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DISTRITO {
            get {
                return this.DISTRITOField;
            }
            set {
                if ((object.ReferenceEquals(this.DISTRITOField, value) != true)) {
                    this.DISTRITOField = value;
                    this.RaisePropertyChanged("DISTRITO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI_PROF {
            get {
                return this.DNI_PROFField;
            }
            set {
                if ((object.ReferenceEquals(this.DNI_PROFField, value) != true)) {
                    this.DNI_PROFField = value;
                    this.RaisePropertyChanged("DNI_PROF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESPECIALIDAD {
            get {
                return this.ESPECIALIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.ESPECIALIDADField, value) != true)) {
                    this.ESPECIALIDADField = value;
                    this.RaisePropertyChanged("ESPECIALIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ESTADO_PROF {
            get {
                return this.ESTADO_PROFField;
            }
            set {
                if ((this.ESTADO_PROFField.Equals(value) != true)) {
                    this.ESTADO_PROFField = value;
                    this.RaisePropertyChanged("ESTADO_PROF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FOTO_PROF {
            get {
                return this.FOTO_PROFField;
            }
            set {
                if ((object.ReferenceEquals(this.FOTO_PROFField, value) != true)) {
                    this.FOTO_PROFField = value;
                    this.RaisePropertyChanged("FOTO_PROF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Registro {
            get {
                return this.Fec_RegistroField;
            }
            set {
                if ((this.Fec_RegistroField.Equals(value) != true)) {
                    this.Fec_RegistroField = value;
                    this.RaisePropertyChanged("Fec_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod {
            get {
                return this.Fec_Ult_ModField;
            }
            set {
                if ((this.Fec_Ult_ModField.Equals(value) != true)) {
                    this.Fec_Ult_ModField = value;
                    this.RaisePropertyChanged("Fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_UBIGEO {
            get {
                return this.ID_UBIGEOField;
            }
            set {
                if ((this.ID_UBIGEOField.Equals(value) != true)) {
                    this.ID_UBIGEOField = value;
                    this.RaisePropertyChanged("ID_UBIGEO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOM_PROF {
            get {
                return this.NOM_PROFField;
            }
            set {
                if ((object.ReferenceEquals(this.NOM_PROFField, value) != true)) {
                    this.NOM_PROFField = value;
                    this.RaisePropertyChanged("NOM_PROF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROVINCIA {
            get {
                return this.PROVINCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.PROVINCIAField, value) != true)) {
                    this.PROVINCIAField = value;
                    this.RaisePropertyChanged("PROVINCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEXO_PROF {
            get {
                return this.SEXO_PROFField;
            }
            set {
                if ((object.ReferenceEquals(this.SEXO_PROFField, value) != true)) {
                    this.SEXO_PROFField = value;
                    this.RaisePropertyChanged("SEXO_PROF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TELF_PROF {
            get {
                return this.TELF_PROFField;
            }
            set {
                if ((object.ReferenceEquals(this.TELF_PROFField, value) != true)) {
                    this.TELF_PROFField = value;
                    this.RaisePropertyChanged("TELF_PROF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstudianteDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ESCUELA")]
    [System.SerializableAttribute()]
    public partial class EstudianteDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APE_ESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_ApoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellNom_ESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DNI_APOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DNI_ESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADO_NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short EST_ESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FEC_NAC_ESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FOTO_ESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Grado_NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_UBIGEOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOM_ESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_ApoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEXO_ESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tel_ApoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APE_EST {
            get {
                return this.APE_ESTField;
            }
            set {
                if ((object.ReferenceEquals(this.APE_ESTField, value) != true)) {
                    this.APE_ESTField = value;
                    this.RaisePropertyChanged("APE_EST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_Apo {
            get {
                return this.Ape_ApoField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_ApoField, value) != true)) {
                    this.Ape_ApoField = value;
                    this.RaisePropertyChanged("Ape_Apo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellNom_EST {
            get {
                return this.ApellNom_ESTField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellNom_ESTField, value) != true)) {
                    this.ApellNom_ESTField = value;
                    this.RaisePropertyChanged("ApellNom_EST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DNI_APO {
            get {
                return this.DNI_APOField;
            }
            set {
                if ((this.DNI_APOField.Equals(value) != true)) {
                    this.DNI_APOField = value;
                    this.RaisePropertyChanged("DNI_APO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DNI_EST {
            get {
                return this.DNI_ESTField;
            }
            set {
                if ((this.DNI_ESTField.Equals(value) != true)) {
                    this.DNI_ESTField = value;
                    this.RaisePropertyChanged("DNI_EST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO_NOMBRE {
            get {
                return this.ESTADO_NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADO_NOMBREField, value) != true)) {
                    this.ESTADO_NOMBREField = value;
                    this.RaisePropertyChanged("ESTADO_NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short EST_EST {
            get {
                return this.EST_ESTField;
            }
            set {
                if ((this.EST_ESTField.Equals(value) != true)) {
                    this.EST_ESTField = value;
                    this.RaisePropertyChanged("EST_EST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FEC_NAC_EST {
            get {
                return this.FEC_NAC_ESTField;
            }
            set {
                if ((this.FEC_NAC_ESTField.Equals(value) != true)) {
                    this.FEC_NAC_ESTField = value;
                    this.RaisePropertyChanged("FEC_NAC_EST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FOTO_EST {
            get {
                return this.FOTO_ESTField;
            }
            set {
                if ((object.ReferenceEquals(this.FOTO_ESTField, value) != true)) {
                    this.FOTO_ESTField = value;
                    this.RaisePropertyChanged("FOTO_EST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Registro {
            get {
                return this.Fec_RegistroField;
            }
            set {
                if ((this.Fec_RegistroField.Equals(value) != true)) {
                    this.Fec_RegistroField = value;
                    this.RaisePropertyChanged("Fec_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod {
            get {
                return this.Fec_Ult_ModField;
            }
            set {
                if ((this.Fec_Ult_ModField.Equals(value) != true)) {
                    this.Fec_Ult_ModField = value;
                    this.RaisePropertyChanged("Fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grado_Nom {
            get {
                return this.Grado_NomField;
            }
            set {
                if ((object.ReferenceEquals(this.Grado_NomField, value) != true)) {
                    this.Grado_NomField = value;
                    this.RaisePropertyChanged("Grado_Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_UBIGEO {
            get {
                return this.ID_UBIGEOField;
            }
            set {
                if ((this.ID_UBIGEOField.Equals(value) != true)) {
                    this.ID_UBIGEOField = value;
                    this.RaisePropertyChanged("ID_UBIGEO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOM_EST {
            get {
                return this.NOM_ESTField;
            }
            set {
                if ((object.ReferenceEquals(this.NOM_ESTField, value) != true)) {
                    this.NOM_ESTField = value;
                    this.RaisePropertyChanged("NOM_EST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Apo {
            get {
                return this.Nom_ApoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_ApoField, value) != true)) {
                    this.Nom_ApoField = value;
                    this.RaisePropertyChanged("Nom_Apo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEXO_EST {
            get {
                return this.SEXO_ESTField;
            }
            set {
                if ((object.ReferenceEquals(this.SEXO_ESTField, value) != true)) {
                    this.SEXO_ESTField = value;
                    this.RaisePropertyChanged("SEXO_EST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_Apo {
            get {
                return this.Tel_ApoField;
            }
            set {
                if ((object.ReferenceEquals(this.Tel_ApoField, value) != true)) {
                    this.Tel_ApoField = value;
                    this.RaisePropertyChanged("Tel_Apo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyConsultas.IServicioConsultas")]
    public interface IServicioConsultas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ConsultarSeccionesPorProfesorId", ReplyAction="http://tempuri.org/IServicioConsultas/ConsultarSeccionesPorProfesorIdResponse")]
        WEB_CONSULTAS.ProxyConsultas.SeccionDC[] ConsultarSeccionesPorProfesorId(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ConsultarSeccionesPorProfesorId", ReplyAction="http://tempuri.org/IServicioConsultas/ConsultarSeccionesPorProfesorIdResponse")]
        System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyConsultas.SeccionDC[]> ConsultarSeccionesPorProfesorIdAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ContarAlumnosPorSeccionId", ReplyAction="http://tempuri.org/IServicioConsultas/ContarAlumnosPorSeccionIdResponse")]
        short ContarAlumnosPorSeccionId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ContarAlumnosPorSeccionId", ReplyAction="http://tempuri.org/IServicioConsultas/ContarAlumnosPorSeccionIdResponse")]
        System.Threading.Tasks.Task<short> ContarAlumnosPorSeccionIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ConsultarMatriculaPorAlumnoDNI", ReplyAction="http://tempuri.org/IServicioConsultas/ConsultarMatriculaPorAlumnoDNIResponse")]
        WEB_CONSULTAS.ProxyConsultas.MatriculaDC ConsultarMatriculaPorAlumnoDNI(int dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ConsultarMatriculaPorAlumnoDNI", ReplyAction="http://tempuri.org/IServicioConsultas/ConsultarMatriculaPorAlumnoDNIResponse")]
        System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyConsultas.MatriculaDC> ConsultarMatriculaPorAlumnoDNIAsync(int dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ConsultarMatriculadosPorFechas", ReplyAction="http://tempuri.org/IServicioConsultas/ConsultarMatriculadosPorFechasResponse")]
        WEB_CONSULTAS.ProxyConsultas.MatriculaDC[] ConsultarMatriculadosPorFechas(System.DateTime Fec_ini, System.DateTime Fec_Fin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ConsultarMatriculadosPorFechas", ReplyAction="http://tempuri.org/IServicioConsultas/ConsultarMatriculadosPorFechasResponse")]
        System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyConsultas.MatriculaDC[]> ConsultarMatriculadosPorFechasAsync(System.DateTime Fec_ini, System.DateTime Fec_Fin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ConsultarProfesoresPorEspecialidad", ReplyAction="http://tempuri.org/IServicioConsultas/ConsultarProfesoresPorEspecialidadResponse")]
        WEB_CONSULTAS.ProxyConsultas.ProfesorDC[] ConsultarProfesoresPorEspecialidad(string Especialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ConsultarProfesoresPorEspecialidad", ReplyAction="http://tempuri.org/IServicioConsultas/ConsultarProfesoresPorEspecialidadResponse")]
        System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyConsultas.ProfesorDC[]> ConsultarProfesoresPorEspecialidadAsync(string Especialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ConsultarEstudiantesPorGradoId", ReplyAction="http://tempuri.org/IServicioConsultas/ConsultarEstudiantesPorGradoIdResponse")]
        WEB_CONSULTAS.ProxyConsultas.EstudianteDC[] ConsultarEstudiantesPorGradoId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ConsultarEstudiantesPorGradoId", ReplyAction="http://tempuri.org/IServicioConsultas/ConsultarEstudiantesPorGradoIdResponse")]
        System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyConsultas.EstudianteDC[]> ConsultarEstudiantesPorGradoIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioConsultasChannel : WEB_CONSULTAS.ProxyConsultas.IServicioConsultas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioConsultasClient : System.ServiceModel.ClientBase<WEB_CONSULTAS.ProxyConsultas.IServicioConsultas>, WEB_CONSULTAS.ProxyConsultas.IServicioConsultas {
        
        public ServicioConsultasClient() {
        }
        
        public ServicioConsultasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioConsultasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WEB_CONSULTAS.ProxyConsultas.SeccionDC[] ConsultarSeccionesPorProfesorId(string strCodigo) {
            return base.Channel.ConsultarSeccionesPorProfesorId(strCodigo);
        }
        
        public System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyConsultas.SeccionDC[]> ConsultarSeccionesPorProfesorIdAsync(string strCodigo) {
            return base.Channel.ConsultarSeccionesPorProfesorIdAsync(strCodigo);
        }
        
        public short ContarAlumnosPorSeccionId(int id) {
            return base.Channel.ContarAlumnosPorSeccionId(id);
        }
        
        public System.Threading.Tasks.Task<short> ContarAlumnosPorSeccionIdAsync(int id) {
            return base.Channel.ContarAlumnosPorSeccionIdAsync(id);
        }
        
        public WEB_CONSULTAS.ProxyConsultas.MatriculaDC ConsultarMatriculaPorAlumnoDNI(int dni) {
            return base.Channel.ConsultarMatriculaPorAlumnoDNI(dni);
        }
        
        public System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyConsultas.MatriculaDC> ConsultarMatriculaPorAlumnoDNIAsync(int dni) {
            return base.Channel.ConsultarMatriculaPorAlumnoDNIAsync(dni);
        }
        
        public WEB_CONSULTAS.ProxyConsultas.MatriculaDC[] ConsultarMatriculadosPorFechas(System.DateTime Fec_ini, System.DateTime Fec_Fin) {
            return base.Channel.ConsultarMatriculadosPorFechas(Fec_ini, Fec_Fin);
        }
        
        public System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyConsultas.MatriculaDC[]> ConsultarMatriculadosPorFechasAsync(System.DateTime Fec_ini, System.DateTime Fec_Fin) {
            return base.Channel.ConsultarMatriculadosPorFechasAsync(Fec_ini, Fec_Fin);
        }
        
        public WEB_CONSULTAS.ProxyConsultas.ProfesorDC[] ConsultarProfesoresPorEspecialidad(string Especialidad) {
            return base.Channel.ConsultarProfesoresPorEspecialidad(Especialidad);
        }
        
        public System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyConsultas.ProfesorDC[]> ConsultarProfesoresPorEspecialidadAsync(string Especialidad) {
            return base.Channel.ConsultarProfesoresPorEspecialidadAsync(Especialidad);
        }
        
        public WEB_CONSULTAS.ProxyConsultas.EstudianteDC[] ConsultarEstudiantesPorGradoId(int id) {
            return base.Channel.ConsultarEstudiantesPorGradoId(id);
        }
        
        public System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyConsultas.EstudianteDC[]> ConsultarEstudiantesPorGradoIdAsync(int id) {
            return base.Channel.ConsultarEstudiantesPorGradoIdAsync(id);
        }
    }
}
