//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_CONSULTAS.ProxyCurso {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CursoDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ESCUELA")]
    [System.SerializableAttribute()]
    public partial class CursoDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short COD_CURSOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Est_CursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_GRADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_CursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short COD_CURSO {
            get {
                return this.COD_CURSOField;
            }
            set {
                if ((this.COD_CURSOField.Equals(value) != true)) {
                    this.COD_CURSOField = value;
                    this.RaisePropertyChanged("COD_CURSO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Est_Curso {
            get {
                return this.Est_CursoField;
            }
            set {
                if ((this.Est_CursoField.Equals(value) != true)) {
                    this.Est_CursoField = value;
                    this.RaisePropertyChanged("Est_Curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Registro {
            get {
                return this.Fec_RegistroField;
            }
            set {
                if ((this.Fec_RegistroField.Equals(value) != true)) {
                    this.Fec_RegistroField = value;
                    this.RaisePropertyChanged("Fec_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod {
            get {
                return this.Fec_Ult_ModField;
            }
            set {
                if ((this.Fec_Ult_ModField.Equals(value) != true)) {
                    this.Fec_Ult_ModField = value;
                    this.RaisePropertyChanged("Fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_GRADO {
            get {
                return this.ID_GRADOField;
            }
            set {
                if ((this.ID_GRADOField.Equals(value) != true)) {
                    this.ID_GRADOField = value;
                    this.RaisePropertyChanged("ID_GRADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Curso {
            get {
                return this.Nom_CursoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_CursoField, value) != true)) {
                    this.Nom_CursoField = value;
                    this.RaisePropertyChanged("Nom_Curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCurso.IServicioCurso")]
    public interface IServicioCurso {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/ConsultarCurso", ReplyAction="http://tempuri.org/IServicioCurso/ConsultarCursoResponse")]
        WEB_CONSULTAS.ProxyCurso.CursoDC ConsultarCurso(short Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/ConsultarCurso", ReplyAction="http://tempuri.org/IServicioCurso/ConsultarCursoResponse")]
        System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyCurso.CursoDC> ConsultarCursoAsync(short Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/ListarCurso", ReplyAction="http://tempuri.org/IServicioCurso/ListarCursoResponse")]
        WEB_CONSULTAS.ProxyCurso.CursoDC[] ListarCurso();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/ListarCurso", ReplyAction="http://tempuri.org/IServicioCurso/ListarCursoResponse")]
        System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyCurso.CursoDC[]> ListarCursoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/InsertarCurso", ReplyAction="http://tempuri.org/IServicioCurso/InsertarCursoResponse")]
        bool InsertarCurso(WEB_CONSULTAS.ProxyCurso.CursoDC objCursoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/InsertarCurso", ReplyAction="http://tempuri.org/IServicioCurso/InsertarCursoResponse")]
        System.Threading.Tasks.Task<bool> InsertarCursoAsync(WEB_CONSULTAS.ProxyCurso.CursoDC objCursoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/ActualizarCurso", ReplyAction="http://tempuri.org/IServicioCurso/ActualizarCursoResponse")]
        bool ActualizarCurso(WEB_CONSULTAS.ProxyCurso.CursoDC objCursoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/ActualizarCurso", ReplyAction="http://tempuri.org/IServicioCurso/ActualizarCursoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarCursoAsync(WEB_CONSULTAS.ProxyCurso.CursoDC objCursoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/EliminarCurso", ReplyAction="http://tempuri.org/IServicioCurso/EliminarCursoResponse")]
        bool EliminarCurso(short Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/EliminarCurso", ReplyAction="http://tempuri.org/IServicioCurso/EliminarCursoResponse")]
        System.Threading.Tasks.Task<bool> EliminarCursoAsync(short Codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioCursoChannel : WEB_CONSULTAS.ProxyCurso.IServicioCurso, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCursoClient : System.ServiceModel.ClientBase<WEB_CONSULTAS.ProxyCurso.IServicioCurso>, WEB_CONSULTAS.ProxyCurso.IServicioCurso {
        
        public ServicioCursoClient() {
        }
        
        public ServicioCursoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCursoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCursoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCursoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WEB_CONSULTAS.ProxyCurso.CursoDC ConsultarCurso(short Codigo) {
            return base.Channel.ConsultarCurso(Codigo);
        }
        
        public System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyCurso.CursoDC> ConsultarCursoAsync(short Codigo) {
            return base.Channel.ConsultarCursoAsync(Codigo);
        }
        
        public WEB_CONSULTAS.ProxyCurso.CursoDC[] ListarCurso() {
            return base.Channel.ListarCurso();
        }
        
        public System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyCurso.CursoDC[]> ListarCursoAsync() {
            return base.Channel.ListarCursoAsync();
        }
        
        public bool InsertarCurso(WEB_CONSULTAS.ProxyCurso.CursoDC objCursoDC) {
            return base.Channel.InsertarCurso(objCursoDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarCursoAsync(WEB_CONSULTAS.ProxyCurso.CursoDC objCursoDC) {
            return base.Channel.InsertarCursoAsync(objCursoDC);
        }
        
        public bool ActualizarCurso(WEB_CONSULTAS.ProxyCurso.CursoDC objCursoDC) {
            return base.Channel.ActualizarCurso(objCursoDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarCursoAsync(WEB_CONSULTAS.ProxyCurso.CursoDC objCursoDC) {
            return base.Channel.ActualizarCursoAsync(objCursoDC);
        }
        
        public bool EliminarCurso(short Codigo) {
            return base.Channel.EliminarCurso(Codigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarCursoAsync(short Codigo) {
            return base.Channel.EliminarCursoAsync(Codigo);
        }
    }
}
