//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_CONSULTAS.ProxyMatricula {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatriculaDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ESCUELA")]
    [System.SerializableAttribute()]
    public partial class MatriculaDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_EstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellNom_venField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_MATRICULAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DNI_ESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ESTADO_MATRIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FEC_MATRIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_SECCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_EstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_SeccField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_Est {
            get {
                return this.Ape_EstField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_EstField, value) != true)) {
                    this.Ape_EstField = value;
                    this.RaisePropertyChanged("Ape_Est");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellNom_ven {
            get {
                return this.ApellNom_venField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellNom_venField, value) != true)) {
                    this.ApellNom_venField = value;
                    this.RaisePropertyChanged("ApellNom_ven");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COD_MATRICULA {
            get {
                return this.COD_MATRICULAField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_MATRICULAField, value) != true)) {
                    this.COD_MATRICULAField = value;
                    this.RaisePropertyChanged("COD_MATRICULA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DNI_EST {
            get {
                return this.DNI_ESTField;
            }
            set {
                if ((this.DNI_ESTField.Equals(value) != true)) {
                    this.DNI_ESTField = value;
                    this.RaisePropertyChanged("DNI_EST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ESTADO_MATRI {
            get {
                return this.ESTADO_MATRIField;
            }
            set {
                if ((this.ESTADO_MATRIField.Equals(value) != true)) {
                    this.ESTADO_MATRIField = value;
                    this.RaisePropertyChanged("ESTADO_MATRI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FEC_MATRI {
            get {
                return this.FEC_MATRIField;
            }
            set {
                if ((this.FEC_MATRIField.Equals(value) != true)) {
                    this.FEC_MATRIField = value;
                    this.RaisePropertyChanged("FEC_MATRI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Registro {
            get {
                return this.Fec_RegistroField;
            }
            set {
                if ((this.Fec_RegistroField.Equals(value) != true)) {
                    this.Fec_RegistroField = value;
                    this.RaisePropertyChanged("Fec_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod {
            get {
                return this.Fec_Ult_ModField;
            }
            set {
                if ((this.Fec_Ult_ModField.Equals(value) != true)) {
                    this.Fec_Ult_ModField = value;
                    this.RaisePropertyChanged("Fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_SECCION {
            get {
                return this.ID_SECCIONField;
            }
            set {
                if ((this.ID_SECCIONField.Equals(value) != true)) {
                    this.ID_SECCIONField = value;
                    this.RaisePropertyChanged("ID_SECCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Est {
            get {
                return this.Nom_EstField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_EstField, value) != true)) {
                    this.Nom_EstField = value;
                    this.RaisePropertyChanged("Nom_Est");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Secc {
            get {
                return this.Nom_SeccField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_SeccField, value) != true)) {
                    this.Nom_SeccField = value;
                    this.RaisePropertyChanged("Nom_Secc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyMatricula.IServicioMatricula")]
    public interface IServicioMatricula {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/ConsultarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/ConsultarMatriculaResponse")]
        WEB_CONSULTAS.ProxyMatricula.MatriculaDC ConsultarMatricula(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/ConsultarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/ConsultarMatriculaResponse")]
        System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyMatricula.MatriculaDC> ConsultarMatriculaAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/InsertarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/InsertarMatriculaResponse")]
        bool InsertarMatricula(WEB_CONSULTAS.ProxyMatricula.MatriculaDC objMatriculaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/InsertarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/InsertarMatriculaResponse")]
        System.Threading.Tasks.Task<bool> InsertarMatriculaAsync(WEB_CONSULTAS.ProxyMatricula.MatriculaDC objMatriculaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/ActualizarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/ActualizarMatriculaResponse")]
        bool ActualizarMatricula(WEB_CONSULTAS.ProxyMatricula.MatriculaDC objMatriculaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/ActualizarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/ActualizarMatriculaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarMatriculaAsync(WEB_CONSULTAS.ProxyMatricula.MatriculaDC objMatriculaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/EliminarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/EliminarMatriculaResponse")]
        bool EliminarMatricula(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/EliminarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/EliminarMatriculaResponse")]
        System.Threading.Tasks.Task<bool> EliminarMatriculaAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/ListarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/ListarMatriculaResponse")]
        WEB_CONSULTAS.ProxyMatricula.MatriculaDC[] ListarMatricula();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/ListarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/ListarMatriculaResponse")]
        System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyMatricula.MatriculaDC[]> ListarMatriculaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioMatriculaChannel : WEB_CONSULTAS.ProxyMatricula.IServicioMatricula, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioMatriculaClient : System.ServiceModel.ClientBase<WEB_CONSULTAS.ProxyMatricula.IServicioMatricula>, WEB_CONSULTAS.ProxyMatricula.IServicioMatricula {
        
        public ServicioMatriculaClient() {
        }
        
        public ServicioMatriculaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioMatriculaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioMatriculaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioMatriculaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WEB_CONSULTAS.ProxyMatricula.MatriculaDC ConsultarMatricula(string strCodigo) {
            return base.Channel.ConsultarMatricula(strCodigo);
        }
        
        public System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyMatricula.MatriculaDC> ConsultarMatriculaAsync(string strCodigo) {
            return base.Channel.ConsultarMatriculaAsync(strCodigo);
        }
        
        public bool InsertarMatricula(WEB_CONSULTAS.ProxyMatricula.MatriculaDC objMatriculaDC) {
            return base.Channel.InsertarMatricula(objMatriculaDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarMatriculaAsync(WEB_CONSULTAS.ProxyMatricula.MatriculaDC objMatriculaDC) {
            return base.Channel.InsertarMatriculaAsync(objMatriculaDC);
        }
        
        public bool ActualizarMatricula(WEB_CONSULTAS.ProxyMatricula.MatriculaDC objMatriculaDC) {
            return base.Channel.ActualizarMatricula(objMatriculaDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarMatriculaAsync(WEB_CONSULTAS.ProxyMatricula.MatriculaDC objMatriculaDC) {
            return base.Channel.ActualizarMatriculaAsync(objMatriculaDC);
        }
        
        public bool EliminarMatricula(string strCodigo) {
            return base.Channel.EliminarMatricula(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarMatriculaAsync(string strCodigo) {
            return base.Channel.EliminarMatriculaAsync(strCodigo);
        }
        
        public WEB_CONSULTAS.ProxyMatricula.MatriculaDC[] ListarMatricula() {
            return base.Channel.ListarMatricula();
        }
        
        public System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyMatricula.MatriculaDC[]> ListarMatriculaAsync() {
            return base.Channel.ListarMatriculaAsync();
        }
    }
}
