//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyProfesor
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfesorDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ESCUELA")]
    public partial class ProfesorDC : object
    {
        
        private string APE_PROFField;
        
        private string ApeNom_ProfField;
        
        private string COD_PROFField;
        
        private string CORREO_PROFField;
        
        private string DEPARTAMENTOField;
        
        private string DISTRITOField;
        
        private string DNI_PROFField;
        
        private string ESPECIALIDADField;
        
        private short ESTADO_PROFField;
        
        private string EstadoField;
        
        private byte[] FOTO_PROFField;
        
        private System.DateTime Fec_RegistroField;
        
        private System.DateTime Fec_Ult_ModField;
        
        private int ID_UBIGEOField;
        
        private string NOM_PROFField;
        
        private string PROVINCIAField;
        
        private string SEXO_PROFField;
        
        private string TELF_PROFField;
        
        private string Usu_RegistroField;
        
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APE_PROF
        {
            get
            {
                return this.APE_PROFField;
            }
            set
            {
                this.APE_PROFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeNom_Prof
        {
            get
            {
                return this.ApeNom_ProfField;
            }
            set
            {
                this.ApeNom_ProfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COD_PROF
        {
            get
            {
                return this.COD_PROFField;
            }
            set
            {
                this.COD_PROFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CORREO_PROF
        {
            get
            {
                return this.CORREO_PROFField;
            }
            set
            {
                this.CORREO_PROFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DEPARTAMENTO
        {
            get
            {
                return this.DEPARTAMENTOField;
            }
            set
            {
                this.DEPARTAMENTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DISTRITO
        {
            get
            {
                return this.DISTRITOField;
            }
            set
            {
                this.DISTRITOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI_PROF
        {
            get
            {
                return this.DNI_PROFField;
            }
            set
            {
                this.DNI_PROFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESPECIALIDAD
        {
            get
            {
                return this.ESPECIALIDADField;
            }
            set
            {
                this.ESPECIALIDADField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ESTADO_PROF
        {
            get
            {
                return this.ESTADO_PROFField;
            }
            set
            {
                this.ESTADO_PROFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FOTO_PROF
        {
            get
            {
                return this.FOTO_PROFField;
            }
            set
            {
                this.FOTO_PROFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Registro
        {
            get
            {
                return this.Fec_RegistroField;
            }
            set
            {
                this.Fec_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod
        {
            get
            {
                return this.Fec_Ult_ModField;
            }
            set
            {
                this.Fec_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_UBIGEO
        {
            get
            {
                return this.ID_UBIGEOField;
            }
            set
            {
                this.ID_UBIGEOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOM_PROF
        {
            get
            {
                return this.NOM_PROFField;
            }
            set
            {
                this.NOM_PROFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROVINCIA
        {
            get
            {
                return this.PROVINCIAField;
            }
            set
            {
                this.PROVINCIAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEXO_PROF
        {
            get
            {
                return this.SEXO_PROFField;
            }
            set
            {
                this.SEXO_PROFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TELF_PROF
        {
            get
            {
                return this.TELF_PROFField;
            }
            set
            {
                this.TELF_PROFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro
        {
            get
            {
                return this.Usu_RegistroField;
            }
            set
            {
                this.Usu_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod
        {
            get
            {
                return this.Usu_Ult_ModField;
            }
            set
            {
                this.Usu_Ult_ModField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyProfesor.IServicioProfesor")]
    public interface IServicioProfesor
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ConsultarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ConsultarProfesorResponse")]
        ProxyProfesor.ProfesorDC ConsultarProfesor(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ConsultarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ConsultarProfesorResponse")]
        System.Threading.Tasks.Task<ProxyProfesor.ProfesorDC> ConsultarProfesorAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ListarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ListarProfesorResponse")]
        System.Collections.Generic.List<ProxyProfesor.ProfesorDC> ListarProfesor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ListarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ListarProfesorResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyProfesor.ProfesorDC>> ListarProfesorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/InsertarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/InsertarProfesorResponse")]
        bool InsertarProfesor(ProxyProfesor.ProfesorDC objProfesorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/InsertarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/InsertarProfesorResponse")]
        System.Threading.Tasks.Task<bool> InsertarProfesorAsync(ProxyProfesor.ProfesorDC objProfesorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ActualizarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ActualizarProfesorResponse")]
        bool ActualizarProfesor(ProxyProfesor.ProfesorDC objProfesorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ActualizarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ActualizarProfesorResponse")]
        System.Threading.Tasks.Task<bool> ActualizarProfesorAsync(ProxyProfesor.ProfesorDC objProfesorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/EliminarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/EliminarProfesorResponse")]
        bool EliminarProfesor(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/EliminarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/EliminarProfesorResponse")]
        System.Threading.Tasks.Task<bool> EliminarProfesorAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ExisteProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ExisteProfesorResponse")]
        bool ExisteProfesor(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ExisteProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ExisteProfesorResponse")]
        System.Threading.Tasks.Task<bool> ExisteProfesorAsync(string dni);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioProfesorChannel : ProxyProfesor.IServicioProfesor, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioProfesorClient : System.ServiceModel.ClientBase<ProxyProfesor.IServicioProfesor>, ProxyProfesor.IServicioProfesor
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioProfesorClient() : 
                base(ServicioProfesorClient.GetDefaultBinding(), ServicioProfesorClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioProfesor.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioProfesorClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioProfesorClient.GetBindingForEndpoint(endpointConfiguration), ServicioProfesorClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioProfesorClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioProfesorClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioProfesorClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioProfesorClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioProfesorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ProxyProfesor.ProfesorDC ConsultarProfesor(string strCodigo)
        {
            return base.Channel.ConsultarProfesor(strCodigo);
        }
        
        public System.Threading.Tasks.Task<ProxyProfesor.ProfesorDC> ConsultarProfesorAsync(string strCodigo)
        {
            return base.Channel.ConsultarProfesorAsync(strCodigo);
        }
        
        public System.Collections.Generic.List<ProxyProfesor.ProfesorDC> ListarProfesor()
        {
            return base.Channel.ListarProfesor();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyProfesor.ProfesorDC>> ListarProfesorAsync()
        {
            return base.Channel.ListarProfesorAsync();
        }
        
        public bool InsertarProfesor(ProxyProfesor.ProfesorDC objProfesorDC)
        {
            return base.Channel.InsertarProfesor(objProfesorDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarProfesorAsync(ProxyProfesor.ProfesorDC objProfesorDC)
        {
            return base.Channel.InsertarProfesorAsync(objProfesorDC);
        }
        
        public bool ActualizarProfesor(ProxyProfesor.ProfesorDC objProfesorDC)
        {
            return base.Channel.ActualizarProfesor(objProfesorDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarProfesorAsync(ProxyProfesor.ProfesorDC objProfesorDC)
        {
            return base.Channel.ActualizarProfesorAsync(objProfesorDC);
        }
        
        public bool EliminarProfesor(string strCodigo)
        {
            return base.Channel.EliminarProfesor(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarProfesorAsync(string strCodigo)
        {
            return base.Channel.EliminarProfesorAsync(strCodigo);
        }
        
        public bool ExisteProfesor(string dni)
        {
            return base.Channel.ExisteProfesor(dni);
        }
        
        public System.Threading.Tasks.Task<bool> ExisteProfesorAsync(string dni)
        {
            return base.Channel.ExisteProfesorAsync(dni);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioProfesor))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioProfesor))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ESCUELA/ServicioProfesor/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioProfesorClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioProfesor);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioProfesorClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioProfesor);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioProfesor,
        }
    }
}
