//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyMatricula
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatriculaDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ESCUELA")]
    public partial class MatriculaDC : object
    {
        
        private string Ape_EstField;
        
        private string ApellNom_venField;
        
        private string COD_MATRICULAField;
        
        private int DNI_ESTField;
        
        private short ESTADO_MATRIField;
        
        private string EstadoField;
        
        private System.DateTime FEC_MATRIField;
        
        private System.DateTime Fec_RegistroField;
        
        private System.DateTime Fec_Ult_ModField;
        
        private short ID_SECCIONField;
        
        private string Nom_EstField;
        
        private string Nom_SeccField;
        
        private string Usu_RegistroField;
        
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_Est
        {
            get
            {
                return this.Ape_EstField;
            }
            set
            {
                this.Ape_EstField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellNom_ven
        {
            get
            {
                return this.ApellNom_venField;
            }
            set
            {
                this.ApellNom_venField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COD_MATRICULA
        {
            get
            {
                return this.COD_MATRICULAField;
            }
            set
            {
                this.COD_MATRICULAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DNI_EST
        {
            get
            {
                return this.DNI_ESTField;
            }
            set
            {
                this.DNI_ESTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ESTADO_MATRI
        {
            get
            {
                return this.ESTADO_MATRIField;
            }
            set
            {
                this.ESTADO_MATRIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FEC_MATRI
        {
            get
            {
                return this.FEC_MATRIField;
            }
            set
            {
                this.FEC_MATRIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Registro
        {
            get
            {
                return this.Fec_RegistroField;
            }
            set
            {
                this.Fec_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod
        {
            get
            {
                return this.Fec_Ult_ModField;
            }
            set
            {
                this.Fec_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_SECCION
        {
            get
            {
                return this.ID_SECCIONField;
            }
            set
            {
                this.ID_SECCIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Est
        {
            get
            {
                return this.Nom_EstField;
            }
            set
            {
                this.Nom_EstField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Secc
        {
            get
            {
                return this.Nom_SeccField;
            }
            set
            {
                this.Nom_SeccField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro
        {
            get
            {
                return this.Usu_RegistroField;
            }
            set
            {
                this.Usu_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod
        {
            get
            {
                return this.Usu_Ult_ModField;
            }
            set
            {
                this.Usu_Ult_ModField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyMatricula.IServicioMatricula")]
    public interface IServicioMatricula
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/ConsultarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/ConsultarMatriculaResponse")]
        ProxyMatricula.MatriculaDC ConsultarMatricula(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/ConsultarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/ConsultarMatriculaResponse")]
        System.Threading.Tasks.Task<ProxyMatricula.MatriculaDC> ConsultarMatriculaAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/InsertarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/InsertarMatriculaResponse")]
        bool InsertarMatricula(ProxyMatricula.MatriculaDC objMatriculaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/InsertarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/InsertarMatriculaResponse")]
        System.Threading.Tasks.Task<bool> InsertarMatriculaAsync(ProxyMatricula.MatriculaDC objMatriculaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/ActualizarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/ActualizarMatriculaResponse")]
        bool ActualizarMatricula(ProxyMatricula.MatriculaDC objMatriculaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/ActualizarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/ActualizarMatriculaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarMatriculaAsync(ProxyMatricula.MatriculaDC objMatriculaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/EliminarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/EliminarMatriculaResponse")]
        bool EliminarMatricula(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/EliminarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/EliminarMatriculaResponse")]
        System.Threading.Tasks.Task<bool> EliminarMatriculaAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/ListarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/ListarMatriculaResponse")]
        System.Collections.Generic.List<ProxyMatricula.MatriculaDC> ListarMatricula();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/ListarMatricula", ReplyAction="http://tempuri.org/IServicioMatricula/ListarMatriculaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyMatricula.MatriculaDC>> ListarMatriculaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/ConsultarPorDni", ReplyAction="http://tempuri.org/IServicioMatricula/ConsultarPorDniResponse")]
        short ConsultarPorDni(int DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMatricula/ConsultarPorDni", ReplyAction="http://tempuri.org/IServicioMatricula/ConsultarPorDniResponse")]
        System.Threading.Tasks.Task<short> ConsultarPorDniAsync(int DNI);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioMatriculaChannel : ProxyMatricula.IServicioMatricula, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioMatriculaClient : System.ServiceModel.ClientBase<ProxyMatricula.IServicioMatricula>, ProxyMatricula.IServicioMatricula
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioMatriculaClient() : 
                base(ServicioMatriculaClient.GetDefaultBinding(), ServicioMatriculaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioMatricula.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioMatriculaClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioMatriculaClient.GetBindingForEndpoint(endpointConfiguration), ServicioMatriculaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioMatriculaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioMatriculaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioMatriculaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioMatriculaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioMatriculaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ProxyMatricula.MatriculaDC ConsultarMatricula(string strCodigo)
        {
            return base.Channel.ConsultarMatricula(strCodigo);
        }
        
        public System.Threading.Tasks.Task<ProxyMatricula.MatriculaDC> ConsultarMatriculaAsync(string strCodigo)
        {
            return base.Channel.ConsultarMatriculaAsync(strCodigo);
        }
        
        public bool InsertarMatricula(ProxyMatricula.MatriculaDC objMatriculaDC)
        {
            return base.Channel.InsertarMatricula(objMatriculaDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarMatriculaAsync(ProxyMatricula.MatriculaDC objMatriculaDC)
        {
            return base.Channel.InsertarMatriculaAsync(objMatriculaDC);
        }
        
        public bool ActualizarMatricula(ProxyMatricula.MatriculaDC objMatriculaDC)
        {
            return base.Channel.ActualizarMatricula(objMatriculaDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarMatriculaAsync(ProxyMatricula.MatriculaDC objMatriculaDC)
        {
            return base.Channel.ActualizarMatriculaAsync(objMatriculaDC);
        }
        
        public bool EliminarMatricula(string strCodigo)
        {
            return base.Channel.EliminarMatricula(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarMatriculaAsync(string strCodigo)
        {
            return base.Channel.EliminarMatriculaAsync(strCodigo);
        }
        
        public System.Collections.Generic.List<ProxyMatricula.MatriculaDC> ListarMatricula()
        {
            return base.Channel.ListarMatricula();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyMatricula.MatriculaDC>> ListarMatriculaAsync()
        {
            return base.Channel.ListarMatriculaAsync();
        }
        
        public short ConsultarPorDni(int DNI)
        {
            return base.Channel.ConsultarPorDni(DNI);
        }
        
        public System.Threading.Tasks.Task<short> ConsultarPorDniAsync(int DNI)
        {
            return base.Channel.ConsultarPorDniAsync(DNI);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioMatricula))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioMatricula))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ESCUELA/ServicioMatricula/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioMatriculaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioMatricula);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioMatriculaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioMatricula);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioMatricula,
        }
    }
}
