//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyEstudiante
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstudianteDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ESCUELA")]
    public partial class EstudianteDC : object
    {
        
        private string APE_ESTField;
        
        private string Ape_ApoField;
        
        private string ApellNom_ESTField;
        
        private int DNI_APOField;
        
        private int DNI_ESTField;
        
        private string DepartamentoField;
        
        private string DistritoField;
        
        private short EST_ESTField;
        
        private string EstadoField;
        
        private System.DateTime FEC_NAC_ESTField;
        
        private byte[] FOTO_ESTField;
        
        private System.DateTime Fec_RegistroField;
        
        private System.DateTime Fec_Ult_ModField;
        
        private string Grado_NomField;
        
        private int ID_UBIGEOField;
        
        private string NOM_ESTField;
        
        private string Nom_ApoField;
        
        private string ProvinciaField;
        
        private string SEXO_ESTField;
        
        private string Tel_ApoField;
        
        private string Usu_RegistroField;
        
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APE_EST
        {
            get
            {
                return this.APE_ESTField;
            }
            set
            {
                this.APE_ESTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_Apo
        {
            get
            {
                return this.Ape_ApoField;
            }
            set
            {
                this.Ape_ApoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellNom_EST
        {
            get
            {
                return this.ApellNom_ESTField;
            }
            set
            {
                this.ApellNom_ESTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DNI_APO
        {
            get
            {
                return this.DNI_APOField;
            }
            set
            {
                this.DNI_APOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DNI_EST
        {
            get
            {
                return this.DNI_ESTField;
            }
            set
            {
                this.DNI_ESTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito
        {
            get
            {
                return this.DistritoField;
            }
            set
            {
                this.DistritoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short EST_EST
        {
            get
            {
                return this.EST_ESTField;
            }
            set
            {
                this.EST_ESTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FEC_NAC_EST
        {
            get
            {
                return this.FEC_NAC_ESTField;
            }
            set
            {
                this.FEC_NAC_ESTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FOTO_EST
        {
            get
            {
                return this.FOTO_ESTField;
            }
            set
            {
                this.FOTO_ESTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Registro
        {
            get
            {
                return this.Fec_RegistroField;
            }
            set
            {
                this.Fec_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod
        {
            get
            {
                return this.Fec_Ult_ModField;
            }
            set
            {
                this.Fec_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grado_Nom
        {
            get
            {
                return this.Grado_NomField;
            }
            set
            {
                this.Grado_NomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_UBIGEO
        {
            get
            {
                return this.ID_UBIGEOField;
            }
            set
            {
                this.ID_UBIGEOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOM_EST
        {
            get
            {
                return this.NOM_ESTField;
            }
            set
            {
                this.NOM_ESTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Apo
        {
            get
            {
                return this.Nom_ApoField;
            }
            set
            {
                this.Nom_ApoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEXO_EST
        {
            get
            {
                return this.SEXO_ESTField;
            }
            set
            {
                this.SEXO_ESTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_Apo
        {
            get
            {
                return this.Tel_ApoField;
            }
            set
            {
                this.Tel_ApoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro
        {
            get
            {
                return this.Usu_RegistroField;
            }
            set
            {
                this.Usu_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod
        {
            get
            {
                return this.Usu_Ult_ModField;
            }
            set
            {
                this.Usu_Ult_ModField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyEstudiante.IServicioEstudiante")]
    public interface IServicioEstudiante
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/ConsultarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/ConsultarEstudianteResponse")]
        ProxyEstudiante.EstudianteDC ConsultarEstudiante(int strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/ConsultarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/ConsultarEstudianteResponse")]
        System.Threading.Tasks.Task<ProxyEstudiante.EstudianteDC> ConsultarEstudianteAsync(int strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/ListarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/ListarEstudianteResponse")]
        System.Collections.Generic.List<ProxyEstudiante.EstudianteDC> ListarEstudiante();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/ListarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/ListarEstudianteResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyEstudiante.EstudianteDC>> ListarEstudianteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/InsertarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/InsertarEstudianteResponse")]
        bool InsertarEstudiante(ProxyEstudiante.EstudianteDC objEstudianteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/InsertarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/InsertarEstudianteResponse")]
        System.Threading.Tasks.Task<bool> InsertarEstudianteAsync(ProxyEstudiante.EstudianteDC objEstudianteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/ActualizarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/ActualizarEstudianteResponse")]
        bool ActualizarEstudiante(ProxyEstudiante.EstudianteDC objEstudianteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/ActualizarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/ActualizarEstudianteResponse")]
        System.Threading.Tasks.Task<bool> ActualizarEstudianteAsync(ProxyEstudiante.EstudianteDC objEstudianteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/EliminarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/EliminarEstudianteResponse")]
        bool EliminarEstudiante(int strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/EliminarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/EliminarEstudianteResponse")]
        System.Threading.Tasks.Task<bool> EliminarEstudianteAsync(int strCodigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioEstudianteChannel : ProxyEstudiante.IServicioEstudiante, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioEstudianteClient : System.ServiceModel.ClientBase<ProxyEstudiante.IServicioEstudiante>, ProxyEstudiante.IServicioEstudiante
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioEstudianteClient() : 
                base(ServicioEstudianteClient.GetDefaultBinding(), ServicioEstudianteClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioEstudiante.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEstudianteClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioEstudianteClient.GetBindingForEndpoint(endpointConfiguration), ServicioEstudianteClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEstudianteClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioEstudianteClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEstudianteClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioEstudianteClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEstudianteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ProxyEstudiante.EstudianteDC ConsultarEstudiante(int strCodigo)
        {
            return base.Channel.ConsultarEstudiante(strCodigo);
        }
        
        public System.Threading.Tasks.Task<ProxyEstudiante.EstudianteDC> ConsultarEstudianteAsync(int strCodigo)
        {
            return base.Channel.ConsultarEstudianteAsync(strCodigo);
        }
        
        public System.Collections.Generic.List<ProxyEstudiante.EstudianteDC> ListarEstudiante()
        {
            return base.Channel.ListarEstudiante();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyEstudiante.EstudianteDC>> ListarEstudianteAsync()
        {
            return base.Channel.ListarEstudianteAsync();
        }
        
        public bool InsertarEstudiante(ProxyEstudiante.EstudianteDC objEstudianteDC)
        {
            return base.Channel.InsertarEstudiante(objEstudianteDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarEstudianteAsync(ProxyEstudiante.EstudianteDC objEstudianteDC)
        {
            return base.Channel.InsertarEstudianteAsync(objEstudianteDC);
        }
        
        public bool ActualizarEstudiante(ProxyEstudiante.EstudianteDC objEstudianteDC)
        {
            return base.Channel.ActualizarEstudiante(objEstudianteDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarEstudianteAsync(ProxyEstudiante.EstudianteDC objEstudianteDC)
        {
            return base.Channel.ActualizarEstudianteAsync(objEstudianteDC);
        }
        
        public bool EliminarEstudiante(int strCodigo)
        {
            return base.Channel.EliminarEstudiante(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarEstudianteAsync(int strCodigo)
        {
            return base.Channel.EliminarEstudianteAsync(strCodigo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioEstudiante))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioEstudiante))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ESCUELA/ServicioEstudiante/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioEstudianteClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioEstudiante);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioEstudianteClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioEstudiante);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioEstudiante,
        }
    }
}
