//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_CONSULTAS.ProxyProfesor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfesorDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ESCUELA")]
    [System.SerializableAttribute()]
    public partial class ProfesorDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APE_PROFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeNom_ProfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_PROFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CORREO_PROFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DEPARTAMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DISTRITOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNI_PROFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESPECIALIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ESTADO_PROFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FOTO_PROFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_UBIGEOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOM_PROFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROVINCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEXO_PROFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TELF_PROFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APE_PROF {
            get {
                return this.APE_PROFField;
            }
            set {
                if ((object.ReferenceEquals(this.APE_PROFField, value) != true)) {
                    this.APE_PROFField = value;
                    this.RaisePropertyChanged("APE_PROF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeNom_Prof {
            get {
                return this.ApeNom_ProfField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeNom_ProfField, value) != true)) {
                    this.ApeNom_ProfField = value;
                    this.RaisePropertyChanged("ApeNom_Prof");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COD_PROF {
            get {
                return this.COD_PROFField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_PROFField, value) != true)) {
                    this.COD_PROFField = value;
                    this.RaisePropertyChanged("COD_PROF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CORREO_PROF {
            get {
                return this.CORREO_PROFField;
            }
            set {
                if ((object.ReferenceEquals(this.CORREO_PROFField, value) != true)) {
                    this.CORREO_PROFField = value;
                    this.RaisePropertyChanged("CORREO_PROF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DEPARTAMENTO {
            get {
                return this.DEPARTAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.DEPARTAMENTOField, value) != true)) {
                    this.DEPARTAMENTOField = value;
                    this.RaisePropertyChanged("DEPARTAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DISTRITO {
            get {
                return this.DISTRITOField;
            }
            set {
                if ((object.ReferenceEquals(this.DISTRITOField, value) != true)) {
                    this.DISTRITOField = value;
                    this.RaisePropertyChanged("DISTRITO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI_PROF {
            get {
                return this.DNI_PROFField;
            }
            set {
                if ((object.ReferenceEquals(this.DNI_PROFField, value) != true)) {
                    this.DNI_PROFField = value;
                    this.RaisePropertyChanged("DNI_PROF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESPECIALIDAD {
            get {
                return this.ESPECIALIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.ESPECIALIDADField, value) != true)) {
                    this.ESPECIALIDADField = value;
                    this.RaisePropertyChanged("ESPECIALIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ESTADO_PROF {
            get {
                return this.ESTADO_PROFField;
            }
            set {
                if ((this.ESTADO_PROFField.Equals(value) != true)) {
                    this.ESTADO_PROFField = value;
                    this.RaisePropertyChanged("ESTADO_PROF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FOTO_PROF {
            get {
                return this.FOTO_PROFField;
            }
            set {
                if ((object.ReferenceEquals(this.FOTO_PROFField, value) != true)) {
                    this.FOTO_PROFField = value;
                    this.RaisePropertyChanged("FOTO_PROF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Registro {
            get {
                return this.Fec_RegistroField;
            }
            set {
                if ((this.Fec_RegistroField.Equals(value) != true)) {
                    this.Fec_RegistroField = value;
                    this.RaisePropertyChanged("Fec_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod {
            get {
                return this.Fec_Ult_ModField;
            }
            set {
                if ((this.Fec_Ult_ModField.Equals(value) != true)) {
                    this.Fec_Ult_ModField = value;
                    this.RaisePropertyChanged("Fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_UBIGEO {
            get {
                return this.ID_UBIGEOField;
            }
            set {
                if ((this.ID_UBIGEOField.Equals(value) != true)) {
                    this.ID_UBIGEOField = value;
                    this.RaisePropertyChanged("ID_UBIGEO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOM_PROF {
            get {
                return this.NOM_PROFField;
            }
            set {
                if ((object.ReferenceEquals(this.NOM_PROFField, value) != true)) {
                    this.NOM_PROFField = value;
                    this.RaisePropertyChanged("NOM_PROF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROVINCIA {
            get {
                return this.PROVINCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.PROVINCIAField, value) != true)) {
                    this.PROVINCIAField = value;
                    this.RaisePropertyChanged("PROVINCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEXO_PROF {
            get {
                return this.SEXO_PROFField;
            }
            set {
                if ((object.ReferenceEquals(this.SEXO_PROFField, value) != true)) {
                    this.SEXO_PROFField = value;
                    this.RaisePropertyChanged("SEXO_PROF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TELF_PROF {
            get {
                return this.TELF_PROFField;
            }
            set {
                if ((object.ReferenceEquals(this.TELF_PROFField, value) != true)) {
                    this.TELF_PROFField = value;
                    this.RaisePropertyChanged("TELF_PROF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyProfesor.IServicioProfesor")]
    public interface IServicioProfesor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ConsultarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ConsultarProfesorResponse")]
        WEB_CONSULTAS.ProxyProfesor.ProfesorDC ConsultarProfesor(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ConsultarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ConsultarProfesorResponse")]
        System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyProfesor.ProfesorDC> ConsultarProfesorAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ListarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ListarProfesorResponse")]
        WEB_CONSULTAS.ProxyProfesor.ProfesorDC[] ListarProfesor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ListarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ListarProfesorResponse")]
        System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyProfesor.ProfesorDC[]> ListarProfesorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/InsertarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/InsertarProfesorResponse")]
        bool InsertarProfesor(WEB_CONSULTAS.ProxyProfesor.ProfesorDC objProfesorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/InsertarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/InsertarProfesorResponse")]
        System.Threading.Tasks.Task<bool> InsertarProfesorAsync(WEB_CONSULTAS.ProxyProfesor.ProfesorDC objProfesorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ActualizarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ActualizarProfesorResponse")]
        bool ActualizarProfesor(WEB_CONSULTAS.ProxyProfesor.ProfesorDC objProfesorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ActualizarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ActualizarProfesorResponse")]
        System.Threading.Tasks.Task<bool> ActualizarProfesorAsync(WEB_CONSULTAS.ProxyProfesor.ProfesorDC objProfesorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/EliminarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/EliminarProfesorResponse")]
        bool EliminarProfesor(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/EliminarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/EliminarProfesorResponse")]
        System.Threading.Tasks.Task<bool> EliminarProfesorAsync(string strCodigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioProfesorChannel : WEB_CONSULTAS.ProxyProfesor.IServicioProfesor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioProfesorClient : System.ServiceModel.ClientBase<WEB_CONSULTAS.ProxyProfesor.IServicioProfesor>, WEB_CONSULTAS.ProxyProfesor.IServicioProfesor {
        
        public ServicioProfesorClient() {
        }
        
        public ServicioProfesorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioProfesorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProfesorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProfesorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WEB_CONSULTAS.ProxyProfesor.ProfesorDC ConsultarProfesor(string strCodigo) {
            return base.Channel.ConsultarProfesor(strCodigo);
        }
        
        public System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyProfesor.ProfesorDC> ConsultarProfesorAsync(string strCodigo) {
            return base.Channel.ConsultarProfesorAsync(strCodigo);
        }
        
        public WEB_CONSULTAS.ProxyProfesor.ProfesorDC[] ListarProfesor() {
            return base.Channel.ListarProfesor();
        }
        
        public System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyProfesor.ProfesorDC[]> ListarProfesorAsync() {
            return base.Channel.ListarProfesorAsync();
        }
        
        public bool InsertarProfesor(WEB_CONSULTAS.ProxyProfesor.ProfesorDC objProfesorDC) {
            return base.Channel.InsertarProfesor(objProfesorDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarProfesorAsync(WEB_CONSULTAS.ProxyProfesor.ProfesorDC objProfesorDC) {
            return base.Channel.InsertarProfesorAsync(objProfesorDC);
        }
        
        public bool ActualizarProfesor(WEB_CONSULTAS.ProxyProfesor.ProfesorDC objProfesorDC) {
            return base.Channel.ActualizarProfesor(objProfesorDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarProfesorAsync(WEB_CONSULTAS.ProxyProfesor.ProfesorDC objProfesorDC) {
            return base.Channel.ActualizarProfesorAsync(objProfesorDC);
        }
        
        public bool EliminarProfesor(string strCodigo) {
            return base.Channel.EliminarProfesor(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarProfesorAsync(string strCodigo) {
            return base.Channel.EliminarProfesorAsync(strCodigo);
        }
    }
}
