//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxySeccion
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeccionnDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ESCUELA")]
    public partial class SeccionnDC : object
    {
        
        private string Ape_ProfField;
        
        private string Cod_ProfField;
        
        private string EspecialidadField;
        
        private short Estado_profField;
        
        private string GradoYSeccionField;
        
        private short ID_SECCIONField;
        
        private int Id_GradoField;
        
        private string Nom_GradoField;
        
        private string Nom_ProfField;
        
        private string Nom_SeccField;
        
        private string Turno_profField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_Prof
        {
            get
            {
                return this.Ape_ProfField;
            }
            set
            {
                this.Ape_ProfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_Prof
        {
            get
            {
                return this.Cod_ProfField;
            }
            set
            {
                this.Cod_ProfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Especialidad
        {
            get
            {
                return this.EspecialidadField;
            }
            set
            {
                this.EspecialidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Estado_prof
        {
            get
            {
                return this.Estado_profField;
            }
            set
            {
                this.Estado_profField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradoYSeccion
        {
            get
            {
                return this.GradoYSeccionField;
            }
            set
            {
                this.GradoYSeccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_SECCION
        {
            get
            {
                return this.ID_SECCIONField;
            }
            set
            {
                this.ID_SECCIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Grado
        {
            get
            {
                return this.Id_GradoField;
            }
            set
            {
                this.Id_GradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Grado
        {
            get
            {
                return this.Nom_GradoField;
            }
            set
            {
                this.Nom_GradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Prof
        {
            get
            {
                return this.Nom_ProfField;
            }
            set
            {
                this.Nom_ProfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Secc
        {
            get
            {
                return this.Nom_SeccField;
            }
            set
            {
                this.Nom_SeccField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Turno_prof
        {
            get
            {
                return this.Turno_profField;
            }
            set
            {
                this.Turno_profField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxySeccion.IServicioSeccion")]
    public interface IServicioSeccion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSeccion/ListarSeccion", ReplyAction="http://tempuri.org/IServicioSeccion/ListarSeccionResponse")]
        System.Collections.Generic.List<ProxySeccion.SeccionnDC> ListarSeccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSeccion/ListarSeccion", ReplyAction="http://tempuri.org/IServicioSeccion/ListarSeccionResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxySeccion.SeccionnDC>> ListarSeccionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioSeccionChannel : ProxySeccion.IServicioSeccion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioSeccionClient : System.ServiceModel.ClientBase<ProxySeccion.IServicioSeccion>, ProxySeccion.IServicioSeccion
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioSeccionClient() : 
                base(ServicioSeccionClient.GetDefaultBinding(), ServicioSeccionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioSeccion.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioSeccionClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioSeccionClient.GetBindingForEndpoint(endpointConfiguration), ServicioSeccionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioSeccionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioSeccionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioSeccionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioSeccionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioSeccionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxySeccion.SeccionnDC> ListarSeccion()
        {
            return base.Channel.ListarSeccion();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxySeccion.SeccionnDC>> ListarSeccionAsync()
        {
            return base.Channel.ListarSeccionAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioSeccion))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioSeccion))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ESCUELA/ServicioSeccion/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioSeccionClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioSeccion);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioSeccionClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioSeccion);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioSeccion,
        }
    }
}
