//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyCurso
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CursoDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ESCUELA")]
    public partial class CursoDC : object
    {
        
        private short COD_CURSOField;
        
        private short Est_CursoField;
        
        private string EstadoField;
        
        private System.DateTime Fec_RegistroField;
        
        private System.Nullable<System.DateTime> Fec_Ult_ModField;
        
        private short ID_GRADOField;
        
        private string Nom_CursoField;
        
        private string Nom_GradoField;
        
        private string Usu_RegistroField;
        
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short COD_CURSO
        {
            get
            {
                return this.COD_CURSOField;
            }
            set
            {
                this.COD_CURSOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Est_Curso
        {
            get
            {
                return this.Est_CursoField;
            }
            set
            {
                this.Est_CursoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Registro
        {
            get
            {
                return this.Fec_RegistroField;
            }
            set
            {
                this.Fec_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fec_Ult_Mod
        {
            get
            {
                return this.Fec_Ult_ModField;
            }
            set
            {
                this.Fec_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_GRADO
        {
            get
            {
                return this.ID_GRADOField;
            }
            set
            {
                this.ID_GRADOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Curso
        {
            get
            {
                return this.Nom_CursoField;
            }
            set
            {
                this.Nom_CursoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Grado
        {
            get
            {
                return this.Nom_GradoField;
            }
            set
            {
                this.Nom_GradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro
        {
            get
            {
                return this.Usu_RegistroField;
            }
            set
            {
                this.Usu_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod
        {
            get
            {
                return this.Usu_Ult_ModField;
            }
            set
            {
                this.Usu_Ult_ModField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCurso.IServicioCurso")]
    public interface IServicioCurso
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/ConsultarCurso", ReplyAction="http://tempuri.org/IServicioCurso/ConsultarCursoResponse")]
        ProxyCurso.CursoDC ConsultarCurso(short Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/ConsultarCurso", ReplyAction="http://tempuri.org/IServicioCurso/ConsultarCursoResponse")]
        System.Threading.Tasks.Task<ProxyCurso.CursoDC> ConsultarCursoAsync(short Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/ListarCurso", ReplyAction="http://tempuri.org/IServicioCurso/ListarCursoResponse")]
        System.Collections.Generic.List<ProxyCurso.CursoDC> ListarCurso();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/ListarCurso", ReplyAction="http://tempuri.org/IServicioCurso/ListarCursoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCurso.CursoDC>> ListarCursoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/InsertarCurso", ReplyAction="http://tempuri.org/IServicioCurso/InsertarCursoResponse")]
        bool InsertarCurso(ProxyCurso.CursoDC objCursoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/InsertarCurso", ReplyAction="http://tempuri.org/IServicioCurso/InsertarCursoResponse")]
        System.Threading.Tasks.Task<bool> InsertarCursoAsync(ProxyCurso.CursoDC objCursoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/ActualizarCurso", ReplyAction="http://tempuri.org/IServicioCurso/ActualizarCursoResponse")]
        bool ActualizarCurso(ProxyCurso.CursoDC objCursoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/ActualizarCurso", ReplyAction="http://tempuri.org/IServicioCurso/ActualizarCursoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarCursoAsync(ProxyCurso.CursoDC objCursoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/EliminarCurso", ReplyAction="http://tempuri.org/IServicioCurso/EliminarCursoResponse")]
        bool EliminarCurso(short Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/EliminarCurso", ReplyAction="http://tempuri.org/IServicioCurso/EliminarCursoResponse")]
        System.Threading.Tasks.Task<bool> EliminarCursoAsync(short Codigo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioCurso/ExisteCurso", ReplyAction = "http://tempuri.org/IServicioCurso/ExisteCursoResponse")]
        bool ExisteCurso(short codCurso, string nombreCurso);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioCurso/ExisteCurso", ReplyAction = "http://tempuri.org/IServicioCurso/ExisteCursoResponse")]
        System.Threading.Tasks.Task<bool> ExisteCursoAsync(short codCurso, string nombreCurso);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioCursoChannel : ProxyCurso.IServicioCurso, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioCursoClient : System.ServiceModel.ClientBase<ProxyCurso.IServicioCurso>, ProxyCurso.IServicioCurso
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioCursoClient() : 
                base(ServicioCursoClient.GetDefaultBinding(), ServicioCursoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioCurso.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCursoClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioCursoClient.GetBindingForEndpoint(endpointConfiguration), ServicioCursoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCursoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioCursoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCursoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioCursoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCursoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ProxyCurso.CursoDC ConsultarCurso(short Codigo)
        {
            return base.Channel.ConsultarCurso(Codigo);
        }
        
        public System.Threading.Tasks.Task<ProxyCurso.CursoDC> ConsultarCursoAsync(short Codigo)
        {
            return base.Channel.ConsultarCursoAsync(Codigo);
        }
        
        public System.Collections.Generic.List<ProxyCurso.CursoDC> ListarCurso()
        {
            return base.Channel.ListarCurso();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCurso.CursoDC>> ListarCursoAsync()
        {
            return base.Channel.ListarCursoAsync();
        }
        
        public bool InsertarCurso(ProxyCurso.CursoDC objCursoDC)
        {
            return base.Channel.InsertarCurso(objCursoDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarCursoAsync(ProxyCurso.CursoDC objCursoDC)
        {
            return base.Channel.InsertarCursoAsync(objCursoDC);
        }
        
        public bool ActualizarCurso(ProxyCurso.CursoDC objCursoDC)
        {
            return base.Channel.ActualizarCurso(objCursoDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarCursoAsync(ProxyCurso.CursoDC objCursoDC)
        {
            return base.Channel.ActualizarCursoAsync(objCursoDC);
        }
        
        public bool EliminarCurso(short Codigo)
        {
            return base.Channel.EliminarCurso(Codigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarCursoAsync(short Codigo)
        {
            return base.Channel.EliminarCursoAsync(Codigo);
        }

        public bool ExisteCurso(short codCurso, string nombreCurso)
        {
            return base.Channel.ExisteCurso(codCurso, nombreCurso);
        }

        public System.Threading.Tasks.Task<bool> ExisteCursoAsync(short codCurso, string nombreCurso)
        {
            return base.Channel.ExisteCursoAsync(codCurso, nombreCurso);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCurso))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCurso))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ESCUELA/ServicioCurso/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioCursoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioCurso);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioCursoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioCurso);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioCurso,
        }
    }
}
