//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyGrado
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GradoDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ESCUELA")]
    public partial class GradoDC : object
    {
        
        private int ID_GRADOField;
        
        private string NOM_GRADOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_GRADO
        {
            get
            {
                return this.ID_GRADOField;
            }
            set
            {
                this.ID_GRADOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOM_GRADO
        {
            get
            {
                return this.NOM_GRADOField;
            }
            set
            {
                this.NOM_GRADOField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyGrado.IServicioGrado")]
    public interface IServicioGrado
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGrado/ListarGrado", ReplyAction="http://tempuri.org/IServicioGrado/ListarGradoResponse")]
        System.Collections.Generic.List<ProxyGrado.GradoDC> ListarGrado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGrado/ListarGrado", ReplyAction="http://tempuri.org/IServicioGrado/ListarGradoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyGrado.GradoDC>> ListarGradoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioGradoChannel : ProxyGrado.IServicioGrado, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioGradoClient : System.ServiceModel.ClientBase<ProxyGrado.IServicioGrado>, ProxyGrado.IServicioGrado
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioGradoClient() : 
                base(ServicioGradoClient.GetDefaultBinding(), ServicioGradoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioGrado.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioGradoClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioGradoClient.GetBindingForEndpoint(endpointConfiguration), ServicioGradoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioGradoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioGradoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioGradoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioGradoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioGradoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyGrado.GradoDC> ListarGrado()
        {
            return base.Channel.ListarGrado();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyGrado.GradoDC>> ListarGradoAsync()
        {
            return base.Channel.ListarGradoAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioGrado))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioGrado))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ESCUELA/ServicioGrado/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioGradoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioGrado);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioGradoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioGrado);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioGrado,
        }
    }
}
