//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ESCUELA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SistemaDeMatriculaCAEntities : DbContext
    {
        public SistemaDeMatriculaCAEntities()
            : base("name=SistemaDeMatriculaCAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_APODERADO> TB_APODERADO { get; set; }
        public virtual DbSet<TB_CURSO> TB_CURSO { get; set; }
        public virtual DbSet<TB_ESTUDIANTE> TB_ESTUDIANTE { get; set; }
        public virtual DbSet<TB_GRADO> TB_GRADO { get; set; }
        public virtual DbSet<TB_HORARIO> TB_HORARIO { get; set; }
        public virtual DbSet<TB_MATRICULA> TB_MATRICULA { get; set; }
        public virtual DbSet<TB_PROFESOR> TB_PROFESOR { get; set; }
        public virtual DbSet<TB_SECCION> TB_SECCION { get; set; }
        public virtual DbSet<TB_UBIGEO> TB_UBIGEO { get; set; }
        public virtual DbSet<TB_USUARIO> TB_USUARIO { get; set; }
        public virtual DbSet<TB_CURSO_PROFESOR> TB_CURSO_PROFESOR { get; set; }
    
        public virtual int usp_ActualizarApoderado(Nullable<int> dniApo, string nomApo, string apeApo, string sexApo, Nullable<int> ubigeoApo, byte[] fotoApo, Nullable<int> telfApo, string correoApo)
        {
            var dniApoParameter = dniApo.HasValue ?
                new ObjectParameter("dniApo", dniApo) :
                new ObjectParameter("dniApo", typeof(int));
    
            var nomApoParameter = nomApo != null ?
                new ObjectParameter("nomApo", nomApo) :
                new ObjectParameter("nomApo", typeof(string));
    
            var apeApoParameter = apeApo != null ?
                new ObjectParameter("apeApo", apeApo) :
                new ObjectParameter("apeApo", typeof(string));
    
            var sexApoParameter = sexApo != null ?
                new ObjectParameter("sexApo", sexApo) :
                new ObjectParameter("sexApo", typeof(string));
    
            var ubigeoApoParameter = ubigeoApo.HasValue ?
                new ObjectParameter("ubigeoApo", ubigeoApo) :
                new ObjectParameter("ubigeoApo", typeof(int));
    
            var fotoApoParameter = fotoApo != null ?
                new ObjectParameter("fotoApo", fotoApo) :
                new ObjectParameter("fotoApo", typeof(byte[]));
    
            var telfApoParameter = telfApo.HasValue ?
                new ObjectParameter("telfApo", telfApo) :
                new ObjectParameter("telfApo", typeof(int));
    
            var correoApoParameter = correoApo != null ?
                new ObjectParameter("correoApo", correoApo) :
                new ObjectParameter("correoApo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarApoderado", dniApoParameter, nomApoParameter, apeApoParameter, sexApoParameter, ubigeoApoParameter, fotoApoParameter, telfApoParameter, correoApoParameter);
        }
    
        public virtual int usp_ActualizarCurso(Nullable<int> cod_Curso, Nullable<int> id_Grado, string nom_Curso, string usu_Ult_Mod, Nullable<int> est_Curso)
        {
            var cod_CursoParameter = cod_Curso.HasValue ?
                new ObjectParameter("Cod_Curso", cod_Curso) :
                new ObjectParameter("Cod_Curso", typeof(int));
    
            var id_GradoParameter = id_Grado.HasValue ?
                new ObjectParameter("Id_Grado", id_Grado) :
                new ObjectParameter("Id_Grado", typeof(int));
    
            var nom_CursoParameter = nom_Curso != null ?
                new ObjectParameter("Nom_Curso", nom_Curso) :
                new ObjectParameter("Nom_Curso", typeof(string));
    
            var usu_Ult_ModParameter = usu_Ult_Mod != null ?
                new ObjectParameter("Usu_Ult_Mod", usu_Ult_Mod) :
                new ObjectParameter("Usu_Ult_Mod", typeof(string));
    
            var est_CursoParameter = est_Curso.HasValue ?
                new ObjectParameter("Est_Curso", est_Curso) :
                new ObjectParameter("Est_Curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarCurso", cod_CursoParameter, id_GradoParameter, nom_CursoParameter, usu_Ult_ModParameter, est_CursoParameter);
        }
    
        public virtual int usp_ActualizarEstudiante(string dniEst, string nomEst, string apeEst, string sexEst, byte[] fotoEst, Nullable<System.DateTime> fecNacEst, Nullable<int> dniApo, Nullable<int> idUbigeo, Nullable<int> estadoEst, string usu_Ult_Mod)
        {
            var dniEstParameter = dniEst != null ?
                new ObjectParameter("dniEst", dniEst) :
                new ObjectParameter("dniEst", typeof(string));
    
            var nomEstParameter = nomEst != null ?
                new ObjectParameter("nomEst", nomEst) :
                new ObjectParameter("nomEst", typeof(string));
    
            var apeEstParameter = apeEst != null ?
                new ObjectParameter("apeEst", apeEst) :
                new ObjectParameter("apeEst", typeof(string));
    
            var sexEstParameter = sexEst != null ?
                new ObjectParameter("sexEst", sexEst) :
                new ObjectParameter("sexEst", typeof(string));
    
            var fotoEstParameter = fotoEst != null ?
                new ObjectParameter("fotoEst", fotoEst) :
                new ObjectParameter("fotoEst", typeof(byte[]));
    
            var fecNacEstParameter = fecNacEst.HasValue ?
                new ObjectParameter("fecNacEst", fecNacEst) :
                new ObjectParameter("fecNacEst", typeof(System.DateTime));
    
            var dniApoParameter = dniApo.HasValue ?
                new ObjectParameter("dniApo", dniApo) :
                new ObjectParameter("dniApo", typeof(int));
    
            var idUbigeoParameter = idUbigeo.HasValue ?
                new ObjectParameter("IdUbigeo", idUbigeo) :
                new ObjectParameter("IdUbigeo", typeof(int));
    
            var estadoEstParameter = estadoEst.HasValue ?
                new ObjectParameter("estadoEst", estadoEst) :
                new ObjectParameter("estadoEst", typeof(int));
    
            var usu_Ult_ModParameter = usu_Ult_Mod != null ?
                new ObjectParameter("Usu_Ult_Mod", usu_Ult_Mod) :
                new ObjectParameter("Usu_Ult_Mod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarEstudiante", dniEstParameter, nomEstParameter, apeEstParameter, sexEstParameter, fotoEstParameter, fecNacEstParameter, dniApoParameter, idUbigeoParameter, estadoEstParameter, usu_Ult_ModParameter);
        }
    
        public virtual int usp_ActualizarHorario(Nullable<int> idHora, string diaSem, Nullable<System.TimeSpan> horaIni, Nullable<System.TimeSpan> horaFin, Nullable<int> codCurso, Nullable<int> idSecc)
        {
            var idHoraParameter = idHora.HasValue ?
                new ObjectParameter("idHora", idHora) :
                new ObjectParameter("idHora", typeof(int));
    
            var diaSemParameter = diaSem != null ?
                new ObjectParameter("diaSem", diaSem) :
                new ObjectParameter("diaSem", typeof(string));
    
            var horaIniParameter = horaIni.HasValue ?
                new ObjectParameter("horaIni", horaIni) :
                new ObjectParameter("horaIni", typeof(System.TimeSpan));
    
            var horaFinParameter = horaFin.HasValue ?
                new ObjectParameter("horaFin", horaFin) :
                new ObjectParameter("horaFin", typeof(System.TimeSpan));
    
            var codCursoParameter = codCurso.HasValue ?
                new ObjectParameter("codCurso", codCurso) :
                new ObjectParameter("codCurso", typeof(int));
    
            var idSeccParameter = idSecc.HasValue ?
                new ObjectParameter("idSecc", idSecc) :
                new ObjectParameter("idSecc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarHorario", idHoraParameter, diaSemParameter, horaIniParameter, horaFinParameter, codCursoParameter, idSeccParameter);
        }
    
        public virtual int usp_ActualizarMatricula(string codMatri, Nullable<int> dniEst, Nullable<int> idSeccion, Nullable<int> estMatri, string usu_Ult_Mod)
        {
            var codMatriParameter = codMatri != null ?
                new ObjectParameter("codMatri", codMatri) :
                new ObjectParameter("codMatri", typeof(string));
    
            var dniEstParameter = dniEst.HasValue ?
                new ObjectParameter("dniEst", dniEst) :
                new ObjectParameter("dniEst", typeof(int));
    
            var idSeccionParameter = idSeccion.HasValue ?
                new ObjectParameter("idSeccion", idSeccion) :
                new ObjectParameter("idSeccion", typeof(int));
    
            var estMatriParameter = estMatri.HasValue ?
                new ObjectParameter("estMatri", estMatri) :
                new ObjectParameter("estMatri", typeof(int));
    
            var usu_Ult_ModParameter = usu_Ult_Mod != null ?
                new ObjectParameter("Usu_Ult_Mod", usu_Ult_Mod) :
                new ObjectParameter("Usu_Ult_Mod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarMatricula", codMatriParameter, dniEstParameter, idSeccionParameter, estMatriParameter, usu_Ult_ModParameter);
        }
    
        public virtual int usp_ActualizarProfesor(string codProf, string nomProf, string apeProf, string sexProf, byte[] fotoProf, string dniProf, Nullable<int> ubigeoProf, string correoProf, string especialidadProf, string telfProf, Nullable<int> estadoProf, string usu_ult)
        {
            var codProfParameter = codProf != null ?
                new ObjectParameter("codProf", codProf) :
                new ObjectParameter("codProf", typeof(string));
    
            var nomProfParameter = nomProf != null ?
                new ObjectParameter("nomProf", nomProf) :
                new ObjectParameter("nomProf", typeof(string));
    
            var apeProfParameter = apeProf != null ?
                new ObjectParameter("apeProf", apeProf) :
                new ObjectParameter("apeProf", typeof(string));
    
            var sexProfParameter = sexProf != null ?
                new ObjectParameter("sexProf", sexProf) :
                new ObjectParameter("sexProf", typeof(string));
    
            var fotoProfParameter = fotoProf != null ?
                new ObjectParameter("fotoProf", fotoProf) :
                new ObjectParameter("fotoProf", typeof(byte[]));
    
            var dniProfParameter = dniProf != null ?
                new ObjectParameter("dniProf", dniProf) :
                new ObjectParameter("dniProf", typeof(string));
    
            var ubigeoProfParameter = ubigeoProf.HasValue ?
                new ObjectParameter("ubigeoProf", ubigeoProf) :
                new ObjectParameter("ubigeoProf", typeof(int));
    
            var correoProfParameter = correoProf != null ?
                new ObjectParameter("correoProf", correoProf) :
                new ObjectParameter("correoProf", typeof(string));
    
            var especialidadProfParameter = especialidadProf != null ?
                new ObjectParameter("especialidadProf", especialidadProf) :
                new ObjectParameter("especialidadProf", typeof(string));
    
            var telfProfParameter = telfProf != null ?
                new ObjectParameter("telfProf", telfProf) :
                new ObjectParameter("telfProf", typeof(string));
    
            var estadoProfParameter = estadoProf.HasValue ?
                new ObjectParameter("estadoProf", estadoProf) :
                new ObjectParameter("estadoProf", typeof(int));
    
            var usu_ultParameter = usu_ult != null ?
                new ObjectParameter("Usu_ult", usu_ult) :
                new ObjectParameter("Usu_ult", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarProfesor", codProfParameter, nomProfParameter, apeProfParameter, sexProfParameter, fotoProfParameter, dniProfParameter, ubigeoProfParameter, correoProfParameter, especialidadProfParameter, telfProfParameter, estadoProfParameter, usu_ultParameter);
        }
    
        public virtual int usp_ActualizarSeccion(Nullable<int> idSeccion, string nomSeccion, Nullable<int> idGrado, string codProfesor, string turnoProfesor)
        {
            var idSeccionParameter = idSeccion.HasValue ?
                new ObjectParameter("idSeccion", idSeccion) :
                new ObjectParameter("idSeccion", typeof(int));
    
            var nomSeccionParameter = nomSeccion != null ?
                new ObjectParameter("nomSeccion", nomSeccion) :
                new ObjectParameter("nomSeccion", typeof(string));
    
            var idGradoParameter = idGrado.HasValue ?
                new ObjectParameter("idGrado", idGrado) :
                new ObjectParameter("idGrado", typeof(int));
    
            var codProfesorParameter = codProfesor != null ?
                new ObjectParameter("codProfesor", codProfesor) :
                new ObjectParameter("codProfesor", typeof(string));
    
            var turnoProfesorParameter = turnoProfesor != null ?
                new ObjectParameter("turnoProfesor", turnoProfesor) :
                new ObjectParameter("turnoProfesor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarSeccion", idSeccionParameter, nomSeccionParameter, idGradoParameter, codProfesorParameter, turnoProfesorParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarApoderado_Result> usp_ConsultarApoderado(Nullable<int> dniApo)
        {
            var dniApoParameter = dniApo.HasValue ?
                new ObjectParameter("dniApo", dniApo) :
                new ObjectParameter("dniApo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarApoderado_Result>("usp_ConsultarApoderado", dniApoParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarCurso_Result> usp_ConsultarCurso(Nullable<int> cod_Curso)
        {
            var cod_CursoParameter = cod_Curso.HasValue ?
                new ObjectParameter("Cod_Curso", cod_Curso) :
                new ObjectParameter("Cod_Curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarCurso_Result>("usp_ConsultarCurso", cod_CursoParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarEstudiante_Result> usp_ConsultarEstudiante(Nullable<int> dniEst)
        {
            var dniEstParameter = dniEst.HasValue ?
                new ObjectParameter("dniEst", dniEst) :
                new ObjectParameter("dniEst", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarEstudiante_Result>("usp_ConsultarEstudiante", dniEstParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarHorario_Result> usp_ConsultarHorario(Nullable<int> idHora)
        {
            var idHoraParameter = idHora.HasValue ?
                new ObjectParameter("idHora", idHora) :
                new ObjectParameter("idHora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarHorario_Result>("usp_ConsultarHorario", idHoraParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarMatricula_Result> usp_ConsultarMatricula(string codMatri)
        {
            var codMatriParameter = codMatri != null ?
                new ObjectParameter("codMatri", codMatri) :
                new ObjectParameter("codMatri", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarMatricula_Result>("usp_ConsultarMatricula", codMatriParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarProfesor_Result> usp_ConsultarProfesor(string codProf)
        {
            var codProfParameter = codProf != null ?
                new ObjectParameter("codProf", codProf) :
                new ObjectParameter("codProf", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarProfesor_Result>("usp_ConsultarProfesor", codProfParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarSeccion_Result> usp_ConsultarSeccion(Nullable<int> idSeccion)
        {
            var idSeccionParameter = idSeccion.HasValue ?
                new ObjectParameter("idSeccion", idSeccion) :
                new ObjectParameter("idSeccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarSeccion_Result>("usp_ConsultarSeccion", idSeccionParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarUsuario_Result> usp_ConsultarUsuario(string login_Usuario)
        {
            var login_UsuarioParameter = login_Usuario != null ?
                new ObjectParameter("Login_Usuario", login_Usuario) :
                new ObjectParameter("Login_Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarUsuario_Result>("usp_ConsultarUsuario", login_UsuarioParameter);
        }
    
        public virtual int usp_EliminarApoderado(Nullable<int> dniApo)
        {
            var dniApoParameter = dniApo.HasValue ?
                new ObjectParameter("dniApo", dniApo) :
                new ObjectParameter("dniApo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarApoderado", dniApoParameter);
        }
    
        public virtual int usp_EliminarCurso(Nullable<int> cod_Curso)
        {
            var cod_CursoParameter = cod_Curso.HasValue ?
                new ObjectParameter("Cod_Curso", cod_Curso) :
                new ObjectParameter("Cod_Curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarCurso", cod_CursoParameter);
        }
    
        public virtual int usp_EliminarEstudiante(Nullable<int> dniEst)
        {
            var dniEstParameter = dniEst.HasValue ?
                new ObjectParameter("dniEst", dniEst) :
                new ObjectParameter("dniEst", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarEstudiante", dniEstParameter);
        }
    
        public virtual int usp_EliminarHorario(Nullable<int> idHora)
        {
            var idHoraParameter = idHora.HasValue ?
                new ObjectParameter("idHora", idHora) :
                new ObjectParameter("idHora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarHorario", idHoraParameter);
        }
    
        public virtual int usp_EliminarMatricula(string codMatri)
        {
            var codMatriParameter = codMatri != null ?
                new ObjectParameter("codMatri", codMatri) :
                new ObjectParameter("codMatri", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarMatricula", codMatriParameter);
        }
    
        public virtual int usp_EliminarProfesor(string codProf)
        {
            var codProfParameter = codProf != null ?
                new ObjectParameter("codProf", codProf) :
                new ObjectParameter("codProf", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarProfesor", codProfParameter);
        }
    
        public virtual int usp_EliminarSeccion(Nullable<int> idSeccion)
        {
            var idSeccionParameter = idSeccion.HasValue ?
                new ObjectParameter("idSeccion", idSeccion) :
                new ObjectParameter("idSeccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarSeccion", idSeccionParameter);
        }
    
        public virtual int usp_InsertarApoderado(Nullable<int> dniApo, string nomApo, string apeApo, string sexApo, Nullable<int> ubigeoApo, byte[] fotoApo, Nullable<int> telfApo, string correoApo)
        {
            var dniApoParameter = dniApo.HasValue ?
                new ObjectParameter("dniApo", dniApo) :
                new ObjectParameter("dniApo", typeof(int));
    
            var nomApoParameter = nomApo != null ?
                new ObjectParameter("nomApo", nomApo) :
                new ObjectParameter("nomApo", typeof(string));
    
            var apeApoParameter = apeApo != null ?
                new ObjectParameter("apeApo", apeApo) :
                new ObjectParameter("apeApo", typeof(string));
    
            var sexApoParameter = sexApo != null ?
                new ObjectParameter("sexApo", sexApo) :
                new ObjectParameter("sexApo", typeof(string));
    
            var ubigeoApoParameter = ubigeoApo.HasValue ?
                new ObjectParameter("ubigeoApo", ubigeoApo) :
                new ObjectParameter("ubigeoApo", typeof(int));
    
            var fotoApoParameter = fotoApo != null ?
                new ObjectParameter("fotoApo", fotoApo) :
                new ObjectParameter("fotoApo", typeof(byte[]));
    
            var telfApoParameter = telfApo.HasValue ?
                new ObjectParameter("telfApo", telfApo) :
                new ObjectParameter("telfApo", typeof(int));
    
            var correoApoParameter = correoApo != null ?
                new ObjectParameter("correoApo", correoApo) :
                new ObjectParameter("correoApo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarApoderado", dniApoParameter, nomApoParameter, apeApoParameter, sexApoParameter, ubigeoApoParameter, fotoApoParameter, telfApoParameter, correoApoParameter);
        }
    
        public virtual int usp_InsertarCurso(Nullable<int> id_Grado, string nOM_CURSO, string usu_Registro, string usu_Ult_Mod, Nullable<int> est_Curso)
        {
            var id_GradoParameter = id_Grado.HasValue ?
                new ObjectParameter("Id_Grado", id_Grado) :
                new ObjectParameter("Id_Grado", typeof(int));
    
            var nOM_CURSOParameter = nOM_CURSO != null ?
                new ObjectParameter("NOM_CURSO", nOM_CURSO) :
                new ObjectParameter("NOM_CURSO", typeof(string));
    
            var usu_RegistroParameter = usu_Registro != null ?
                new ObjectParameter("Usu_Registro", usu_Registro) :
                new ObjectParameter("Usu_Registro", typeof(string));
    
            var usu_Ult_ModParameter = usu_Ult_Mod != null ?
                new ObjectParameter("Usu_Ult_Mod", usu_Ult_Mod) :
                new ObjectParameter("Usu_Ult_Mod", typeof(string));
    
            var est_CursoParameter = est_Curso.HasValue ?
                new ObjectParameter("Est_Curso", est_Curso) :
                new ObjectParameter("Est_Curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarCurso", id_GradoParameter, nOM_CURSOParameter, usu_RegistroParameter, usu_Ult_ModParameter, est_CursoParameter);
        }
    
        public virtual int usp_InsertarEstudiante(Nullable<int> dniEst, string nomEst, string apeEst, string sexEst, byte[] fotoEst, Nullable<System.DateTime> fecNacEst, Nullable<int> dniApo, Nullable<int> idUbigeo, Nullable<int> estadoEst, string usu_Registro)
        {
            var dniEstParameter = dniEst.HasValue ?
                new ObjectParameter("dniEst", dniEst) :
                new ObjectParameter("dniEst", typeof(int));
    
            var nomEstParameter = nomEst != null ?
                new ObjectParameter("nomEst", nomEst) :
                new ObjectParameter("nomEst", typeof(string));
    
            var apeEstParameter = apeEst != null ?
                new ObjectParameter("apeEst", apeEst) :
                new ObjectParameter("apeEst", typeof(string));
    
            var sexEstParameter = sexEst != null ?
                new ObjectParameter("sexEst", sexEst) :
                new ObjectParameter("sexEst", typeof(string));
    
            var fotoEstParameter = fotoEst != null ?
                new ObjectParameter("fotoEst", fotoEst) :
                new ObjectParameter("fotoEst", typeof(byte[]));
    
            var fecNacEstParameter = fecNacEst.HasValue ?
                new ObjectParameter("fecNacEst", fecNacEst) :
                new ObjectParameter("fecNacEst", typeof(System.DateTime));
    
            var dniApoParameter = dniApo.HasValue ?
                new ObjectParameter("dniApo", dniApo) :
                new ObjectParameter("dniApo", typeof(int));
    
            var idUbigeoParameter = idUbigeo.HasValue ?
                new ObjectParameter("idUbigeo", idUbigeo) :
                new ObjectParameter("idUbigeo", typeof(int));
    
            var estadoEstParameter = estadoEst.HasValue ?
                new ObjectParameter("estadoEst", estadoEst) :
                new ObjectParameter("estadoEst", typeof(int));
    
            var usu_RegistroParameter = usu_Registro != null ?
                new ObjectParameter("Usu_Registro", usu_Registro) :
                new ObjectParameter("Usu_Registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarEstudiante", dniEstParameter, nomEstParameter, apeEstParameter, sexEstParameter, fotoEstParameter, fecNacEstParameter, dniApoParameter, idUbigeoParameter, estadoEstParameter, usu_RegistroParameter);
        }
    
        public virtual int usp_InsertarHorario(string diaSem, Nullable<System.TimeSpan> horaIni, Nullable<System.TimeSpan> horaFin, Nullable<int> codCurso, Nullable<int> idSecc)
        {
            var diaSemParameter = diaSem != null ?
                new ObjectParameter("diaSem", diaSem) :
                new ObjectParameter("diaSem", typeof(string));
    
            var horaIniParameter = horaIni.HasValue ?
                new ObjectParameter("horaIni", horaIni) :
                new ObjectParameter("horaIni", typeof(System.TimeSpan));
    
            var horaFinParameter = horaFin.HasValue ?
                new ObjectParameter("horaFin", horaFin) :
                new ObjectParameter("horaFin", typeof(System.TimeSpan));
    
            var codCursoParameter = codCurso.HasValue ?
                new ObjectParameter("codCurso", codCurso) :
                new ObjectParameter("codCurso", typeof(int));
    
            var idSeccParameter = idSecc.HasValue ?
                new ObjectParameter("idSecc", idSecc) :
                new ObjectParameter("idSecc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarHorario", diaSemParameter, horaIniParameter, horaFinParameter, codCursoParameter, idSeccParameter);
        }
    
        public virtual int usp_InsertarMatricula(Nullable<int> dniEst, Nullable<int> idSeccion, string usu_Registro, Nullable<int> estMatri)
        {
            var dniEstParameter = dniEst.HasValue ?
                new ObjectParameter("dniEst", dniEst) :
                new ObjectParameter("dniEst", typeof(int));
    
            var idSeccionParameter = idSeccion.HasValue ?
                new ObjectParameter("idSeccion", idSeccion) :
                new ObjectParameter("idSeccion", typeof(int));
    
            var usu_RegistroParameter = usu_Registro != null ?
                new ObjectParameter("Usu_Registro", usu_Registro) :
                new ObjectParameter("Usu_Registro", typeof(string));
    
            var estMatriParameter = estMatri.HasValue ?
                new ObjectParameter("estMatri", estMatri) :
                new ObjectParameter("estMatri", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarMatricula", dniEstParameter, idSeccionParameter, usu_RegistroParameter, estMatriParameter);
        }
    
        public virtual int usp_InsertarProfesor(string nomProf, string apeProf, string sexProf, byte[] fotoProf, string dniProf, Nullable<int> ubigeoProf, string correoProf, string especialidadProf, string telfProf, Nullable<int> estadoProf, string usu_registro)
        {
            var nomProfParameter = nomProf != null ?
                new ObjectParameter("nomProf", nomProf) :
                new ObjectParameter("nomProf", typeof(string));
    
            var apeProfParameter = apeProf != null ?
                new ObjectParameter("apeProf", apeProf) :
                new ObjectParameter("apeProf", typeof(string));
    
            var sexProfParameter = sexProf != null ?
                new ObjectParameter("sexProf", sexProf) :
                new ObjectParameter("sexProf", typeof(string));
    
            var fotoProfParameter = fotoProf != null ?
                new ObjectParameter("fotoProf", fotoProf) :
                new ObjectParameter("fotoProf", typeof(byte[]));
    
            var dniProfParameter = dniProf != null ?
                new ObjectParameter("dniProf", dniProf) :
                new ObjectParameter("dniProf", typeof(string));
    
            var ubigeoProfParameter = ubigeoProf.HasValue ?
                new ObjectParameter("ubigeoProf", ubigeoProf) :
                new ObjectParameter("ubigeoProf", typeof(int));
    
            var correoProfParameter = correoProf != null ?
                new ObjectParameter("correoProf", correoProf) :
                new ObjectParameter("correoProf", typeof(string));
    
            var especialidadProfParameter = especialidadProf != null ?
                new ObjectParameter("especialidadProf", especialidadProf) :
                new ObjectParameter("especialidadProf", typeof(string));
    
            var telfProfParameter = telfProf != null ?
                new ObjectParameter("telfProf", telfProf) :
                new ObjectParameter("telfProf", typeof(string));
    
            var estadoProfParameter = estadoProf.HasValue ?
                new ObjectParameter("estadoProf", estadoProf) :
                new ObjectParameter("estadoProf", typeof(int));
    
            var usu_registroParameter = usu_registro != null ?
                new ObjectParameter("Usu_registro", usu_registro) :
                new ObjectParameter("Usu_registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarProfesor", nomProfParameter, apeProfParameter, sexProfParameter, fotoProfParameter, dniProfParameter, ubigeoProfParameter, correoProfParameter, especialidadProfParameter, telfProfParameter, estadoProfParameter, usu_registroParameter);
        }
    
        public virtual int usp_InsertarSeccion(string nomSeccion, Nullable<int> idGrado, string codProfesor, string turnoProfesor)
        {
            var nomSeccionParameter = nomSeccion != null ?
                new ObjectParameter("nomSeccion", nomSeccion) :
                new ObjectParameter("nomSeccion", typeof(string));
    
            var idGradoParameter = idGrado.HasValue ?
                new ObjectParameter("idGrado", idGrado) :
                new ObjectParameter("idGrado", typeof(int));
    
            var codProfesorParameter = codProfesor != null ?
                new ObjectParameter("codProfesor", codProfesor) :
                new ObjectParameter("codProfesor", typeof(string));
    
            var turnoProfesorParameter = turnoProfesor != null ?
                new ObjectParameter("turnoProfesor", turnoProfesor) :
                new ObjectParameter("turnoProfesor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarSeccion", nomSeccionParameter, idGradoParameter, codProfesorParameter, turnoProfesorParameter);
        }
    
        public virtual ObjectResult<usp_ListarApoderado_Result> usp_ListarApoderado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarApoderado_Result>("usp_ListarApoderado");
        }
    
        public virtual ObjectResult<usp_ListarCurso_Result> usp_ListarCurso()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarCurso_Result>("usp_ListarCurso");
        }
    
        public virtual ObjectResult<usp_ListarDistritos_Result> usp_ListarDistritos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarDistritos_Result>("usp_ListarDistritos");
        }
    
        public virtual ObjectResult<usp_ListarEstudiante_Result> usp_ListarEstudiante()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarEstudiante_Result>("usp_ListarEstudiante");
        }
    
        public virtual ObjectResult<usp_ListarGrado_Result> usp_ListarGrado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarGrado_Result>("usp_ListarGrado");
        }
    
        public virtual ObjectResult<usp_ListarHorario_Result> usp_ListarHorario(string ordenarPor)
        {
            var ordenarPorParameter = ordenarPor != null ?
                new ObjectParameter("OrdenarPor", ordenarPor) :
                new ObjectParameter("OrdenarPor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarHorario_Result>("usp_ListarHorario", ordenarPorParameter);
        }
    
        public virtual ObjectResult<usp_ListarMatricula_Result> usp_ListarMatricula()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarMatricula_Result>("usp_ListarMatricula");
        }
    
        public virtual ObjectResult<usp_ListarProfesor_Result> usp_ListarProfesor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarProfesor_Result>("usp_ListarProfesor");
        }
    
        public virtual ObjectResult<usp_ListarSeccion_Result> usp_ListarSeccion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarSeccion_Result>("usp_ListarSeccion");
        }
    
        public virtual ObjectResult<usp_ListarUbicacion_Result> usp_ListarUbicacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarUbicacion_Result>("usp_ListarUbicacion");
        }
    }
}
