//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ESCUELA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_APODERADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_APODERADO()
        {
            this.TB_ESTUDIANTE = new HashSet<TB_ESTUDIANTE>();
        }
    
        public int DNI_APO { get; set; }
        public string NOM_APO { get; set; }
        public string APE_APO { get; set; }
        public string SEXO_APO { get; set; }
        public int ID_UBIGEO { get; set; }
        public byte[] FOTO_APO { get; set; }
        public string TEL_APO { get; set; }
        public string CORREO_APO { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public Nullable<int> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ESTUDIANTE> TB_ESTUDIANTE { get; set; }
        public virtual TB_UBIGEO TB_UBIGEO { get; set; }
    }
}
