//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ESCUELA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CURSO_PROFESOR
    {
        public string COD_PROF { get; set; }
        public int COD_CURSO { get; set; }
        public int ID_SECCION { get; set; }
        public System.DateTime FEC_ASIG { get; set; }
    
        public virtual TB_CURSO TB_CURSO { get; set; }
        public virtual TB_PROFESOR TB_PROFESOR { get; set; }
        public virtual TB_SECCION TB_SECCION { get; set; }
    }
}
