//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ESCUELA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CURSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CURSO()
        {
            this.TB_CURSO_PROFESOR = new HashSet<TB_CURSO_PROFESOR>();
        }
    
        public int COD_CURSO { get; set; }
        public int ID_GRADO { get; set; }
        public string Nom_Curso { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<int> Est_Curso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CURSO_PROFESOR> TB_CURSO_PROFESOR { get; set; }
        public virtual TB_GRADO TB_GRADO { get; set; }
    }
}
