//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ESCUELA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ESTUDIANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ESTUDIANTE()
        {
            this.TB_MATRICULA = new HashSet<TB_MATRICULA>();
        }
    
        public int DNI_EST { get; set; }
        public string NOM_EST { get; set; }
        public string APE_EST { get; set; }
        public string SEXO_EST { get; set; }
        public byte[] FOTO_EST { get; set; }
        public System.DateTime FEC_NAC_EST { get; set; }
        public int DNI_APO { get; set; }
        public int ID_UBIGEO { get; set; }
        public int EST_EST { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
    
        public virtual TB_APODERADO TB_APODERADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MATRICULA> TB_MATRICULA { get; set; }
        public virtual TB_UBIGEO TB_UBIGEO { get; set; }
    }
}
