//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ESCUELA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HORARIO
    {
        public int ID_HORARIO { get; set; }
        public string DIA_SEMANA { get; set; }
        public System.TimeSpan HORA_INICIO { get; set; }
        public System.TimeSpan HORA_FIN { get; set; }
        public int COD_CURSO { get; set; }
        public int ID_SECCION { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public Nullable<int> Est_Horario { get; set; }
    }
}
