//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ESCUELA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROFESOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PROFESOR()
        {
            this.TB_CURSO_PROFESOR = new HashSet<TB_CURSO_PROFESOR>();
            this.TB_SECCION = new HashSet<TB_SECCION>();
        }
    
        public string COD_PROF { get; set; }
        public string NOM_PROF { get; set; }
        public string APE_PROF { get; set; }
        public string SEXO_PROF { get; set; }
        public byte[] FOTO_PROF { get; set; }
        public string DNI_PROF { get; set; }
        public int ID_UBIGEO { get; set; }
        public string CORREO_PROF { get; set; }
        public string ESPECIALIDAD { get; set; }
        public string TELF_PROF { get; set; }
        public int ESTADO_PROF { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CURSO_PROFESOR> TB_CURSO_PROFESOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SECCION> TB_SECCION { get; set; }
        public virtual TB_UBIGEO TB_UBIGEO { get; set; }
    }
}
