//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_CONSULTAS.ProxyEstudiante {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstudianteDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ESCUELA")]
    [System.SerializableAttribute()]
    public partial class EstudianteDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APE_ESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_ApoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellNom_ESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DNI_APOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DNI_ESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADO_NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short EST_ESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FEC_NAC_ESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FOTO_ESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Grado_NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_UBIGEOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOM_ESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_ApoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEXO_ESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tel_ApoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APE_EST {
            get {
                return this.APE_ESTField;
            }
            set {
                if ((object.ReferenceEquals(this.APE_ESTField, value) != true)) {
                    this.APE_ESTField = value;
                    this.RaisePropertyChanged("APE_EST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_Apo {
            get {
                return this.Ape_ApoField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_ApoField, value) != true)) {
                    this.Ape_ApoField = value;
                    this.RaisePropertyChanged("Ape_Apo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellNom_EST {
            get {
                return this.ApellNom_ESTField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellNom_ESTField, value) != true)) {
                    this.ApellNom_ESTField = value;
                    this.RaisePropertyChanged("ApellNom_EST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DNI_APO {
            get {
                return this.DNI_APOField;
            }
            set {
                if ((this.DNI_APOField.Equals(value) != true)) {
                    this.DNI_APOField = value;
                    this.RaisePropertyChanged("DNI_APO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DNI_EST {
            get {
                return this.DNI_ESTField;
            }
            set {
                if ((this.DNI_ESTField.Equals(value) != true)) {
                    this.DNI_ESTField = value;
                    this.RaisePropertyChanged("DNI_EST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO_NOMBRE {
            get {
                return this.ESTADO_NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADO_NOMBREField, value) != true)) {
                    this.ESTADO_NOMBREField = value;
                    this.RaisePropertyChanged("ESTADO_NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short EST_EST {
            get {
                return this.EST_ESTField;
            }
            set {
                if ((this.EST_ESTField.Equals(value) != true)) {
                    this.EST_ESTField = value;
                    this.RaisePropertyChanged("EST_EST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FEC_NAC_EST {
            get {
                return this.FEC_NAC_ESTField;
            }
            set {
                if ((this.FEC_NAC_ESTField.Equals(value) != true)) {
                    this.FEC_NAC_ESTField = value;
                    this.RaisePropertyChanged("FEC_NAC_EST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FOTO_EST {
            get {
                return this.FOTO_ESTField;
            }
            set {
                if ((object.ReferenceEquals(this.FOTO_ESTField, value) != true)) {
                    this.FOTO_ESTField = value;
                    this.RaisePropertyChanged("FOTO_EST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Registro {
            get {
                return this.Fec_RegistroField;
            }
            set {
                if ((this.Fec_RegistroField.Equals(value) != true)) {
                    this.Fec_RegistroField = value;
                    this.RaisePropertyChanged("Fec_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod {
            get {
                return this.Fec_Ult_ModField;
            }
            set {
                if ((this.Fec_Ult_ModField.Equals(value) != true)) {
                    this.Fec_Ult_ModField = value;
                    this.RaisePropertyChanged("Fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grado_Nom {
            get {
                return this.Grado_NomField;
            }
            set {
                if ((object.ReferenceEquals(this.Grado_NomField, value) != true)) {
                    this.Grado_NomField = value;
                    this.RaisePropertyChanged("Grado_Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_UBIGEO {
            get {
                return this.ID_UBIGEOField;
            }
            set {
                if ((this.ID_UBIGEOField.Equals(value) != true)) {
                    this.ID_UBIGEOField = value;
                    this.RaisePropertyChanged("ID_UBIGEO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOM_EST {
            get {
                return this.NOM_ESTField;
            }
            set {
                if ((object.ReferenceEquals(this.NOM_ESTField, value) != true)) {
                    this.NOM_ESTField = value;
                    this.RaisePropertyChanged("NOM_EST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Apo {
            get {
                return this.Nom_ApoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_ApoField, value) != true)) {
                    this.Nom_ApoField = value;
                    this.RaisePropertyChanged("Nom_Apo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEXO_EST {
            get {
                return this.SEXO_ESTField;
            }
            set {
                if ((object.ReferenceEquals(this.SEXO_ESTField, value) != true)) {
                    this.SEXO_ESTField = value;
                    this.RaisePropertyChanged("SEXO_EST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_Apo {
            get {
                return this.Tel_ApoField;
            }
            set {
                if ((object.ReferenceEquals(this.Tel_ApoField, value) != true)) {
                    this.Tel_ApoField = value;
                    this.RaisePropertyChanged("Tel_Apo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyEstudiante.IServicioEstudiante")]
    public interface IServicioEstudiante {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/ConsultarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/ConsultarEstudianteResponse")]
        WEB_CONSULTAS.ProxyEstudiante.EstudianteDC ConsultarEstudiante(int strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/ConsultarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/ConsultarEstudianteResponse")]
        System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyEstudiante.EstudianteDC> ConsultarEstudianteAsync(int strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/ListarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/ListarEstudianteResponse")]
        WEB_CONSULTAS.ProxyEstudiante.EstudianteDC[] ListarEstudiante();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/ListarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/ListarEstudianteResponse")]
        System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyEstudiante.EstudianteDC[]> ListarEstudianteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/InsertarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/InsertarEstudianteResponse")]
        bool InsertarEstudiante(WEB_CONSULTAS.ProxyEstudiante.EstudianteDC objEstudianteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/InsertarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/InsertarEstudianteResponse")]
        System.Threading.Tasks.Task<bool> InsertarEstudianteAsync(WEB_CONSULTAS.ProxyEstudiante.EstudianteDC objEstudianteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/ActualizarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/ActualizarEstudianteResponse")]
        bool ActualizarEstudiante(WEB_CONSULTAS.ProxyEstudiante.EstudianteDC objEstudianteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/ActualizarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/ActualizarEstudianteResponse")]
        System.Threading.Tasks.Task<bool> ActualizarEstudianteAsync(WEB_CONSULTAS.ProxyEstudiante.EstudianteDC objEstudianteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/EliminarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/EliminarEstudianteResponse")]
        bool EliminarEstudiante(int strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstudiante/EliminarEstudiante", ReplyAction="http://tempuri.org/IServicioEstudiante/EliminarEstudianteResponse")]
        System.Threading.Tasks.Task<bool> EliminarEstudianteAsync(int strCodigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEstudianteChannel : WEB_CONSULTAS.ProxyEstudiante.IServicioEstudiante, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEstudianteClient : System.ServiceModel.ClientBase<WEB_CONSULTAS.ProxyEstudiante.IServicioEstudiante>, WEB_CONSULTAS.ProxyEstudiante.IServicioEstudiante {
        
        public ServicioEstudianteClient() {
        }
        
        public ServicioEstudianteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEstudianteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEstudianteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEstudianteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WEB_CONSULTAS.ProxyEstudiante.EstudianteDC ConsultarEstudiante(int strCodigo) {
            return base.Channel.ConsultarEstudiante(strCodigo);
        }
        
        public System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyEstudiante.EstudianteDC> ConsultarEstudianteAsync(int strCodigo) {
            return base.Channel.ConsultarEstudianteAsync(strCodigo);
        }
        
        public WEB_CONSULTAS.ProxyEstudiante.EstudianteDC[] ListarEstudiante() {
            return base.Channel.ListarEstudiante();
        }
        
        public System.Threading.Tasks.Task<WEB_CONSULTAS.ProxyEstudiante.EstudianteDC[]> ListarEstudianteAsync() {
            return base.Channel.ListarEstudianteAsync();
        }
        
        public bool InsertarEstudiante(WEB_CONSULTAS.ProxyEstudiante.EstudianteDC objEstudianteDC) {
            return base.Channel.InsertarEstudiante(objEstudianteDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarEstudianteAsync(WEB_CONSULTAS.ProxyEstudiante.EstudianteDC objEstudianteDC) {
            return base.Channel.InsertarEstudianteAsync(objEstudianteDC);
        }
        
        public bool ActualizarEstudiante(WEB_CONSULTAS.ProxyEstudiante.EstudianteDC objEstudianteDC) {
            return base.Channel.ActualizarEstudiante(objEstudianteDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarEstudianteAsync(WEB_CONSULTAS.ProxyEstudiante.EstudianteDC objEstudianteDC) {
            return base.Channel.ActualizarEstudianteAsync(objEstudianteDC);
        }
        
        public bool EliminarEstudiante(int strCodigo) {
            return base.Channel.EliminarEstudiante(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarEstudianteAsync(int strCodigo) {
            return base.Channel.EliminarEstudianteAsync(strCodigo);
        }
    }
}
